# Generated by Django 6.0.5 on 2026-06-26 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('supplier', '0002_supplier_currency_supplier_tax_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_no', models.CharField(max_length=50, unique=True, verbose_name='应付单号')),
                ('source_type', models.CharField(choices=[('PURCHASE_ORDER', '采购订单'), ('MANUAL', '手工创建')], default='PURCHASE_ORDER', max_length=50)),
                ('source_id', models.IntegerField(blank=True, null=True, verbose_name='来源单据ID')),
                ('currency_code', models.CharField(default='CNY', max_length=10, verbose_name='币种')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='应付总额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='已付金额')),
                ('due_date', models.DateField(verbose_name='到期日')),
                ('status', models.CharField(choices=[('PENDING', '待付款'), ('PARTIAL', '部分付款'), ('PAID', '已付款'), ('OVERDUE', '已逾期'), ('CANCELLED', '已取消')], default='PENDING', max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ap_accounts', to=settings.AUTH_USER_MODEL)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ap_accounts', to='supplier.supplier')),
            ],
            options={
                'verbose_name': '应付账款',
                'verbose_name_plural': '应付账款',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(max_length=50, unique=True, verbose_name='付款单号')),
                ('payment_date', models.DateField(verbose_name='付款日期')),
                ('payment_method', models.CharField(choices=[('CASH', '现金'), ('BANK_TRANSFER', '银行转账'), ('CHECK', '支票'), ('WECHAT', '微信'), ('ALIPAY', '支付宝'), ('OTHER', '其他')], default='BANK_TRANSFER', max_length=20)),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='银行账号')),
                ('currency_code', models.CharField(default='CNY', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='付款金额')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='已核销金额')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_APPROVAL', '待审核'), ('APPROVED', '已审核'), ('COMPLETED', '已支付'), ('CANCELLED', '已作废')], default='DRAFT', max_length=20)),
                ('attachment_id', models.IntegerField(blank=True, null=True, verbose_name='附件ID')),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ap_payments', to=settings.AUTH_USER_MODEL)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='supplier.supplier')),
            ],
            options={
                'verbose_name': '付款单',
                'verbose_name_plural': '付款单',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='操作内容')),
                ('before_value', models.TextField(blank=True, null=True)),
                ('after_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ap_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ap_payable.apaccount')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ap_payable.appayment')),
            ],
            options={
                'verbose_name': '应付操作日志',
                'verbose_name_plural': '应付操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_no', models.CharField(max_length=50, unique=True, verbose_name='核销编号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='核销金额')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ap_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='ap_payable.apaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='ap_payable.appayment')),
            ],
            options={
                'verbose_name': '付款核销',
                'verbose_name_plural': '付款核销',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='apaccount',
            index=models.Index(fields=['ap_no'], name='ap_payable__ap_no_cb5ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='apaccount',
            index=models.Index(fields=['supplier'], name='ap_payable__supplie_65445f_idx'),
        ),
        migrations.AddIndex(
            model_name='apaccount',
            index=models.Index(fields=['status'], name='ap_payable__status_49c021_idx'),
        ),
        migrations.AddIndex(
            model_name='apaccount',
            index=models.Index(fields=['due_date'], name='ap_payable__due_dat_54019d_idx'),
        ),
    ]
