# Generated by Codex on 2026-06-28

import django.db.models.deletion
from django.db import migrations, models


def backfill_purchase_receipt(apps, schema_editor):
    APAccount = apps.get_model('ap_payable', 'APAccount')
    PurchaseReceipt = apps.get_model('purchase', 'PurchaseReceipt')

    for account in APAccount.objects.filter(source_id__isnull=False, purchase_receipt__isnull=True):
        if not PurchaseReceipt.objects.filter(id=account.source_id).exists():
            continue
        account.purchase_receipt_id = account.source_id
        if account.source_type == 'PURCHASE_ORDER':
            account.source_type = 'PURCHASE_RECEIPT'
        account.save(update_fields=['purchase_receipt', 'source_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('ap_payable', '0002_appayment_cash_account'),
        ('purchase', '0003_purchaseorder_submitted_by_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apaccount',
            name='source_type',
            field=models.CharField(
                choices=[
                    ('PURCHASE_ORDER', '采购订单'),
                    ('PURCHASE_RECEIPT', '采购入库单'),
                    ('MANUAL', '手工创建'),
                ],
                default='PURCHASE_RECEIPT',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name='apaccount',
            name='purchase_receipt',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='ap_accounts',
                to='purchase.purchasereceipt',
                verbose_name='来源入库单',
            ),
        ),
        migrations.RunPython(backfill_purchase_receipt, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='apaccount',
            index=models.Index(fields=['purchase_receipt'], name='ap_payable__purcha_8206f0_idx'),
        ),
    ]
