# Generated by Django 6.0.5 on 2026-06-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap_payable', '0004_appayment_approval_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apaccount',
            new_name='ap_payable__purchas_70a4b8_idx',
            old_name='ap_payable__purcha_8206f0_idx',
        ),
    ]
