# Generated by Codex on 2026-06-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_ap_fields(apps, schema_editor):
    APAccount = apps.get_model('ap_payable', 'APAccount')
    APPayment = apps.get_model('ap_payable', 'APPayment')
    APAllocation = apps.get_model('ap_payable', 'APAllocation')

    for account in APAccount.objects.filter(
        source_document_no_snapshot__isnull=True,
        purchase_receipt_id__isnull=False,
    ).select_related('purchase_receipt'):
        account.source_document_no_snapshot = account.purchase_receipt.receipt_no
        account.save(update_fields=['source_document_no_snapshot'])

    for payment in APPayment.objects.filter(executed_at__isnull=True, status__in=['APPROVED', 'COMPLETED']):
        payment.executed_at = payment.approved_at or payment.updated_at or payment.created_at
        payment.save(update_fields=['executed_at'])

    for allocation in APAllocation.objects.filter(allocation_date__isnull=True):
        allocation.allocation_date = allocation.created_at.date()
        allocation.save(update_fields=['allocation_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('ap_payable', '0005_rename_ap_payable__purcha_8206f0_idx_ap_payable__purchas_70a4b8_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apaccount',
            name='source_document_no_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='来源单号快照'),
        ),
        migrations.AddField(
            model_name='appayment',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='执行时间'),
        ),
        migrations.AddField(
            model_name='apallocation',
            name='allocation_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='核销日期'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SupplierCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_no', models.CharField(max_length=50, unique=True, verbose_name='供应商贷项单号')),
                ('source_document_no_snapshot', models.CharField(max_length=100, verbose_name='来源单号快照')),
                ('source_id', models.IntegerField(blank=True, null=True, verbose_name='来源单据ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='贷项金额')),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='已使用金额')),
                ('note_date', models.DateField(verbose_name='贷项日期')),
                ('status', models.CharField(choices=[('OPEN', '未使用'), ('PARTIAL_USED', '部分使用'), ('USED', '已使用'), ('CANCELLED', '已作废')], default='OPEN', max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_credit_notes', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='supplier.supplier')),
            ],
            options={
                'verbose_name': '供应商贷项',
                'verbose_name_plural': '供应商贷项',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(backfill_ap_fields, migrations.RunPython.noop),
    ]
