# Generated by Django 6.0.5 on 2026-07-03 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_payable', '0007_alter_apallocation_allocation_date'),
        ('tenant', '0003_fix_missing_tenant_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='apaccount',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_accounts', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='apallocation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_allocations', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='apoperationlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_operation_logs', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='appayment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_payments', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='suppliercreditnote',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_credit_notes', to='tenant.tenant'),
        ),
    ]
