# Generated by Django 6.0.5 on 2026-07-03 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_payable', '0008_apaccount_tenant_apallocation_tenant_and_more'),
        ('erp_auth', '0002_erpdepartment_erpuser_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apaccount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ap_accounts', to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='apaccount',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpdepartment'),
        ),
        migrations.AlterField(
            model_name='apallocation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='apoperationlog',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='appayment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ap_payments', to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='appayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ap_payments', to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='appayment',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpdepartment'),
        ),
        migrations.AlterField(
            model_name='appayment',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_ap_payments', to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='suppliercreditnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_credit_notes', to='erp_auth.erpuser'),
        ),
    ]
