# Generated by Django 6.0.5 on 2026-07-12 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_payable', '0009_alter_apaccount_created_by_alter_apaccount_dept_and_more'),
        ('erp_auth', '0002_erpdepartment_erpuser_dept'),
        ('finance', '0004_alter_cashaccounttransaction_operator_and_more'),
        ('supplier', '0007_alter_supplier_account_holder_alter_supplier_address_and_more'),
        ('tenant', '0003_fix_missing_tenant_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_no', models.CharField(max_length=50, unique=True, verbose_name='供应商退款单号')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='退款金额')),
                ('refund_date', models.DateField(verbose_name='退款日期')),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', '银行转账'), ('WECHAT', '微信支付'), ('ALIPAY', '支付宝'), ('CASH', '现金'), ('OTHER', '其他')], default='BANK_TRANSFER', max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='交易流水号/支票号')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('APPROVED', '已审核'), ('COMPLETED', '已收款'), ('CANCELLED', '已作废')], default='DRAFT', max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_supplier_refunds', to='erp_auth.erpuser')),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.cashaccount', verbose_name='收款账户')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_refunds', to='erp_auth.erpuser')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='ap_payable.suppliercreditnote', verbose_name='对应供应商贷项')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpdepartment')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='supplier.supplier')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_refunds', to='tenant.tenant')),
            ],
            options={
                'verbose_name': '供应商退款单',
                'verbose_name_plural': '供应商退款单',
                'ordering': ['-refund_date', '-created_at'],
            },
        ),
    ]
