from core_apps.modules.registry import ModuleDefinition


MODULE = ModuleDefinition(
    key="purchase",
    label="采购管理",
    django_app="business_apps.purchase",
    api_prefix="api/purchase/",
    depends_on=("supplier", "inventory", "platform"),
    menus=(
        {
            "code": "purchase",
            "name": "采购管理",
            "path": "/purchase",
            "icon": "ShoppingCartOutlined",
            "order": 600,
        },
        {
            "code": "purchase:order",
            "name": "采购订单",
            "parent": "purchase",
            "path": "/purchase/orders",
            "component": "purchase/OrderList",
            "icon": "OrderedListOutlined",
            "order": 601,
            "navigation_group": "purchase_center",
            "navigation_order": 202,
        },
        {
            "code": "purchase:order:detail",
            "name": "采购订单详情",
            "parent": "purchase",
            "path": "/purchase/orders/:id",
            "component": "purchase/OrderDetail",
            "order": 602,
            "status": True,
            "hide_in_menu": True,
        },
        {
            "code": "purchase:order:new",
            "name": "新增采购订单",
            "parent": "purchase",
            "path": "/purchase/orders/new",
            "component": "purchase/OrderForm",
            "order": 603,
            "status": True,
            "hide_in_menu": True,
        },
        {
            "code": "purchase:order:edit",
            "name": "编辑采购订单",
            "parent": "purchase",
            "path": "/purchase/orders/:id/edit",
            "component": "purchase/OrderForm",
            "order": 604,
            "status": True,
            "hide_in_menu": True,
        },
        {
            "code": "purchase:receipt",
            "name": "采购入库",
            "parent": "purchase",
            "path": "/purchase/receipts",
            "component": "purchase/ReceiptList",
            "icon": "InboxOutlined",
            "order": 605,
            "navigation_group": "warehouse_logistics",
            "navigation_order": 305,
        },
        {
            "code": "purchase:stats",
            "name": "采购统计",
            "parent": "purchase",
            "path": "/purchase/stats",
            "component": "purchase/PurchaseStats",
            "icon": "BarChartOutlined",
            "order": 606,
            "navigation_group": "purchase_center",
            "navigation_order": 204,
        },
    ),
    permissions=(
        {"code": "purchase:order:view", "name": "查看采购订单", "parent": "purchase:order"},
        {"code": "purchase:stats:view", "name": "查看采购统计", "parent": "purchase:stats"},
        {"code": "purchase:order:create", "name": "创建采购订单", "parent": "purchase:order"},
        {"code": "purchase:order:update", "name": "编辑采购订单", "parent": "purchase:order"},
        {"code": "purchase:order:delete", "name": "删除采购订单", "parent": "purchase:order"},
        {"code": "purchase:order:approve", "name": "审核采购订单", "parent": "purchase:order"},
        {"code": "purchase:order:cancel", "name": "取消采购订单", "parent": "purchase:order"},
        {"code": "purchase:receipt:view", "name": "查看入库单", "parent": "purchase:receipt"},
        {"code": "purchase:receipt:create", "name": "创建入库单", "parent": "purchase:receipt"},
        {"code": "purchase:receipt:complete", "name": "完成入库", "parent": "purchase:receipt"},
        {"code": "purchase:receipt:cancel", "name": "取消入库单", "parent": "purchase:receipt"},
    ),
    features=("采购订单", "采购入库", "采购统计"),
    workflows=("采购下单审批", "采购收货自动生成应付"),
    field_rules=("采购详情页与编辑页为隐藏路由",),
    default_rules=("采购单号默认复用平台编码规则",),
    public_services=("business_apps.purchase.services.PurchaseService",),
    export_metadata={
        "always_include": False,
        "export_enabled": True,
        "export_requires": ("supplier", "inventory", "platform"),
        "must_export_with": ("supplier", "inventory"),
        "feature_pruning": {
            "approval": {
                "code_prunable": False,
                "ui_prunable": True,
                "permission_codes": ("purchase:order:approve",),
            },
            "partial_receipt": {"code_prunable": False, "ui_prunable": True},
            "purchase_return": {"code_prunable": False, "ui_prunable": False},
        },
        "frontend_feature_pages": {
            "approval": ("/purchase/orders", "/purchase/orders/:id"),
            "partial_receipt": ("/purchase/receipts",),
        },
        "seed_data": {"required": False, "keys": ()},
        "attachments_dependency": False,
        "task_log_dependency": True,
    },
)
