from core_apps.modules.registry import ModuleDefinition


MODULE = ModuleDefinition(
    key="platform",
    label="平台基础设施",
    django_app="business_apps.platform",
    api_prefix="api/platform/",
    depends_on=(),
    menus=(
        {
            "code": "platform",
            "name": "基础设施",
            "path": "/platform",
            "icon": "SettingOutlined",
            "order": 900,
        },
        {
            "code": "platform:file",
            "name": "文件中心",
            "parent": "platform",
            "path": "/platform/files",
            "component": "platform/FileCenter",
            "icon": "FolderOutlined",
            "order": 901,
        },
        {
            "code": "platform:dict",
            "name": "字典中心",
            "parent": "platform",
            "path": "/platform/dict",
            "component": "platform/DictCenter",
            "icon": "BookOutlined",
            "order": 902,
        },
        {
            "code": "platform:coderule",
            "name": "编码规则",
            "parent": "platform",
            "path": "/platform/code-rules",
            "component": "platform/CodeRuleCenter",
            "icon": "NumberOutlined",
            "order": 903,
        },
    ),
    permissions=(
        {"code": "platform:file:view", "name": "查看文件", "parent": "platform:file"},
        {"code": "platform:file:upload", "name": "上传文件", "parent": "platform:file"},
        {"code": "platform:file:delete", "name": "删除文件", "parent": "platform:file"},
        {"code": "platform:file:download", "name": "下载文件", "parent": "platform:file"},
        {"code": "platform:dict:view", "name": "查看字典", "parent": "platform:dict"},
        {"code": "platform:dict:create", "name": "创建字典", "parent": "platform:dict"},
        {"code": "platform:dict:update", "name": "修改字典", "parent": "platform:dict"},
        {"code": "platform:dict:delete", "name": "删除字典", "parent": "platform:dict"},
        {"code": "platform:coderule:view", "name": "查看规则", "parent": "platform:coderule"},
        {"code": "platform:coderule:create", "name": "创建规则", "parent": "platform:coderule"},
        {"code": "platform:coderule:update", "name": "修改规则", "parent": "platform:coderule"},
    ),
    features=("文件中心", "数据字典", "编码规则"),
    workflows=("文件上传与归档", "编码规则维护"),
    field_rules=("字典项通过 dict_code 聚合",),
    default_rules=("编码生成能力由 CodeRuleService 对外复用",),
    public_services=("business_apps.platform.services.CodeRuleService",),
    export_metadata={
        "always_include": True,
        "export_enabled": True,
        "must_export_with": (),
        "feature_pruning": {
            "file_center": {"code_prunable": False, "ui_prunable": False, "config_only": True},
            "dict_center": {"code_prunable": False, "ui_prunable": False, "config_only": True},
            "code_rule_center": {"code_prunable": False, "ui_prunable": False, "config_only": True},
        },
        "frontend_feature_pages": {
            "file_center": ("/platform/files",),
            "dict_center": ("/platform/dicts",),
            "code_rule_center": ("/platform/code-rules",),
        },
        "has_frontend_pages": True,
        "seed_data": {"required": True, "keys": ("code_rules", "dict_types")},
        "attachments_dependency": True,
        "task_log_dependency": True,
    },
)
