# Generated by Django 6.0.5 on 2026-06-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountingperiod',
            new_name='accounting__year_919bf3_idx',
            old_name='accounting_a_year_7d2b4e_idx',
        ),
        migrations.RenameIndex(
            model_name='accountingperiod',
            new_name='accounting__start_d_cbbeeb_idx',
            old_name='accounting_a_start_d05542_idx',
        ),
        migrations.RenameIndex(
            model_name='accountingperiod',
            new_name='accounting__status_0ff0cd_idx',
            old_name='accounting_a_status_7c2e83_idx',
        ),
        migrations.RenameIndex(
            model_name='accountsubject',
            new_name='accounting__code_96558a_idx',
            old_name='accounting_a_code_13aadb_idx',
        ),
        migrations.RenameIndex(
            model_name='accountsubject',
            new_name='accounting__categor_a8bd6f_idx',
            old_name='accounting_a_categor_317bc5_idx',
        ),
        migrations.RenameIndex(
            model_name='accountsubject',
            new_name='accounting__enabled_430a66_idx',
            old_name='accounting_a_enabled_242454_idx',
        ),
        migrations.RenameIndex(
            model_name='businesspostinglog',
            new_name='accounting__event_t_13ee6c_idx',
            old_name='accounting_b_event_t_c7672f_idx',
        ),
        migrations.RenameIndex(
            model_name='businesspostinglog',
            new_name='accounting__busines_1fac58_idx',
            old_name='accounting_b_busines_458e1b_idx',
        ),
        migrations.RenameIndex(
            model_name='businesspostinglog',
            new_name='accounting__busines_6463ab_idx',
            old_name='accounting_b_busines_155208_idx',
        ),
        migrations.RenameIndex(
            model_name='voucher',
            new_name='accounting__voucher_fc2273_idx',
            old_name='accounting_v_voucher_4afacf_idx',
        ),
        migrations.RenameIndex(
            model_name='voucher',
            new_name='accounting__voucher_33fe11_idx',
            old_name='accounting_v_voucher_9cbd84_idx',
        ),
        migrations.RenameIndex(
            model_name='voucher',
            new_name='accounting__source__5b303d_idx',
            old_name='accounting_v_source__b457e7_idx',
        ),
        migrations.RenameIndex(
            model_name='voucher',
            new_name='accounting__voucher_e92daa_idx',
            old_name='accounting_v_voucher_12594a_idx',
        ),
        migrations.RenameIndex(
            model_name='voucherline',
            new_name='accounting__subject_c6fe95_idx',
            old_name='accounting_v_subject_ce0d25_idx',
        ),
        migrations.RenameIndex(
            model_name='voucherline',
            new_name='accounting__busines_cb5a92_idx',
            old_name='accounting_v_busines_3726d1_idx',
        ),
    ]
