# Generated by Django 6.0.5 on 2026-07-03 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_rename_accounting_a_year_7d2b4e_idx_accounting__year_919bf3_idx_and_more'),
        ('tenant', '0003_fix_missing_tenant_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingperiod',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_periods', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='accountsubject',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_subjects', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='businesspostinglog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_posting_logs', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_lines', to='tenant.tenant'),
        ),
    ]
