# Generated by Django 6.0.5 on 2026-07-03 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accountingperiod_tenant_accountsubject_tenant_and_more'),
        ('erp_auth', '0002_erpdepartment_erpuser_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_accounting_periods', to='erp_auth.erpuser', verbose_name='关闭人'),
        ),
        migrations.AlterField(
            model_name='accountsubject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_account_subjects', to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='businesspostinglog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_posting_logs', to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_vouchers', to='erp_auth.erpuser', verbose_name='过账人'),
        ),
    ]
