# Generated by Django 6.0.5 on 2026-07-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_alter_accountingperiod_closed_by_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="accountingperiod",
            unique_together={("tenant", "year", "month")},
        ),
        migrations.RemoveIndex(
            model_name="accountingperiod",
            name="accounting__year_919bf3_idx",
        ),
        migrations.AddIndex(
            model_name="accountingperiod",
            index=models.Index(fields=["tenant", "year", "month"], name="accounting__tenant__8c61bd_idx"),
        ),
    ]
