# Generated by Django 6.0.5 on 2026-07-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_accountingperiod_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountsubject",
            name="code",
            field=models.CharField(max_length=20, verbose_name="科目编码"),
        ),
        migrations.AlterUniqueTogether(
            name="accountsubject",
            unique_together={("tenant", "code")},
        ),
        migrations.RemoveIndex(
            model_name="accountsubject",
            name="accounting__code_96558a_idx",
        ),
        migrations.AddIndex(
            model_name="accountsubject",
            index=models.Index(fields=["tenant", "code"], name="accounting__tenant__15ef4d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="businesspostinglog",
            unique_together={("tenant", "event_type", "business_type", "business_id")},
        ),
    ]
