# Generated by Django 6.0.5 on 2026-06-30 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from core_apps.blueprints.models import GenerationJob, SystemBlueprint, SystemBlueprintVersion, SystemInstance
from core_apps.tenant.models import Tenant, TenantConfigSnapshot, TenantModuleState, TenantUser


MODEL_NAMES = (
    Tenant,
    SystemBlueprint,
    SystemBlueprintVersion,
    SystemInstance,
    GenerationJob,
    TenantConfigSnapshot,
    TenantModuleState,
    TenantUser,
)


def _create_missing_system_tables(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())
    for model in MODEL_NAMES:
        if model._meta.db_table in existing_tables:
            continue
        schema_editor.create_model(model)
        existing_tables.add(model._meta.db_table)


def _add_missing_system_constraints(apps, schema_editor):
    constraint_specs = (
        (SystemBlueprintVersion, models.UniqueConstraint(fields=("blueprint", "version"), name="uniq_blueprint_version")),
        (TenantModuleState, models.UniqueConstraint(fields=("tenant", "module_key"), name="uniq_tenant_module_state")),
        (TenantUser, models.UniqueConstraint(fields=("tenant", "user"), name="uniq_tenant_user")),
    )
    with schema_editor.connection.cursor() as cursor:
        for model, constraint in constraint_specs:
            constraints = schema_editor.connection.introspection.get_constraints(cursor, model._meta.db_table)
            if constraint.name in constraints:
                continue
            schema_editor.add_constraint(model, constraint)


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_create_missing_system_tables, migrations.RunPython.noop),
                migrations.RunPython(_add_missing_system_constraints, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Tenant',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(max_length=100, unique=True, verbose_name='租户编码')),
                        ('name', models.CharField(max_length=100, verbose_name='租户名称')),
                        ('status', models.CharField(choices=[('ACTIVE', '启用'), ('INACTIVE', '停用'), ('ARCHIVED', '归档')], default='ACTIVE', max_length=20, verbose_name='状态')),
                        ('industry', models.CharField(blank=True, max_length=100, verbose_name='行业')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                    ],
                    options={
                        'verbose_name': '租户',
                        'verbose_name_plural': '租户',
                        'db_table': 'sys_tenants',
                        'ordering': ['name', 'id'],
                    },
                ),
                migrations.CreateModel(
                    name='SystemBlueprint',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('key', models.CharField(max_length=100, unique=True, verbose_name='蓝图标识')),
                        ('name', models.CharField(max_length=100, verbose_name='蓝图名称')),
                        ('description', models.TextField(blank=True, verbose_name='描述')),
                        ('industry', models.CharField(blank=True, max_length=100, verbose_name='行业')),
                        ('status', models.CharField(choices=[('DRAFT', '草稿'), ('ACTIVE', '启用'), ('ARCHIVED', '归档')], default='DRAFT', max_length=20, verbose_name='状态')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blueprints', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                    ],
                    options={
                        'verbose_name': '系统蓝图',
                        'verbose_name_plural': '系统蓝图',
                        'db_table': 'sys_blueprints',
                        'ordering': ['name', 'id'],
                    },
                ),
                migrations.CreateModel(
                    name='SystemBlueprintVersion',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('version', models.CharField(max_length=50, verbose_name='版本号')),
                        ('config_json', models.JSONField(blank=True, default=dict, verbose_name='配置快照')),
                        ('change_note', models.CharField(blank=True, max_length=500, verbose_name='变更说明')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                        ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                        ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='system.systemblueprint', verbose_name='蓝图')),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blueprint_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                    ],
                    options={
                        'verbose_name': '蓝图版本',
                        'verbose_name_plural': '蓝图版本',
                        'db_table': 'sys_blueprint_versions',
                        'ordering': ['-created_at', '-id'],
                    },
                ),
                migrations.CreateModel(
                    name='SystemInstance',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100, verbose_name='实例名称')),
                        ('mode', models.CharField(choices=[('SAAS', 'SaaS'), ('CODE_EXPORT', '代码导出')], max_length=20, verbose_name='模式')),
                        ('status', models.CharField(choices=[('DRAFT', '草稿'), ('GENERATING', '生成中'), ('ACTIVE', '可用'), ('FAILED', '失败'), ('ARCHIVED', '归档')], default='DRAFT', max_length=20, verbose_name='状态')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                        ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='system.systemblueprint', verbose_name='蓝图')),
                        ('blueprint_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='system.systemblueprintversion', verbose_name='蓝图版本')),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_system_instances', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                        ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='system.tenant', verbose_name='租户')),
                    ],
                    options={
                        'verbose_name': '系统实例',
                        'verbose_name_plural': '系统实例',
                        'db_table': 'sys_instances',
                        'ordering': ['-created_at', '-id'],
                    },
                ),
                migrations.CreateModel(
                    name='GenerationJob',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('job_type', models.CharField(choices=[('CREATE_SAAS', '创建 SaaS'), ('EXPORT_CODE', '导出代码')], max_length=20, verbose_name='任务类型')),
                        ('status', models.CharField(choices=[('PENDING', '待执行'), ('RUNNING', '执行中'), ('SUCCEEDED', '成功'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='状态')),
                        ('payload_json', models.JSONField(blank=True, default=dict, verbose_name='输入参数')),
                        ('result_json', models.JSONField(blank=True, default=dict, verbose_name='输出结果')),
                        ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                        ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                        ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                        ('blueprint_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_jobs', to='system.systemblueprintversion', verbose_name='蓝图版本')),
                        ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='system.systeminstance', verbose_name='实例')),
                    ],
                    options={
                        'verbose_name': '生成任务',
                        'verbose_name_plural': '生成任务',
                        'db_table': 'sys_generation_jobs',
                        'ordering': ['-id'],
                    },
                ),
                migrations.CreateModel(
                    name='TenantConfigSnapshot',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('config_json', models.JSONField(blank=True, default=dict, verbose_name='配置快照')),
                        ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='应用时间')),
                        ('blueprint_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_snapshots', to='system.systemblueprintversion', verbose_name='蓝图版本')),
                        ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_snapshots', to='system.tenant', verbose_name='租户')),
                    ],
                    options={
                        'verbose_name': '租户配置快照',
                        'verbose_name_plural': '租户配置快照',
                        'db_table': 'sys_tenant_config_snapshots',
                        'ordering': ['-applied_at', '-id'],
                    },
                ),
                migrations.CreateModel(
                    name='TenantModuleState',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('module_key', models.CharField(max_length=100, verbose_name='模块标识')),
                        ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                        ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_states', to='system.tenant', verbose_name='租户')),
                    ],
                    options={
                        'verbose_name': '租户模块开关',
                        'verbose_name_plural': '租户模块开关',
                        'db_table': 'sys_tenant_module_states',
                        'ordering': ['tenant_id', 'module_key'],
                    },
                ),
                migrations.CreateModel(
                    name='TenantUser',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('is_owner', models.BooleanField(default=False, verbose_name='是否所有者')),
                        ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                        ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='system.tenant', verbose_name='租户')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                    ],
                    options={
                        'verbose_name': '租户成员',
                        'verbose_name_plural': '租户成员',
                        'db_table': 'sys_tenant_users',
                        'ordering': ['tenant_id', 'user_id', 'id'],
                    },
                ),
                migrations.AddConstraint(
                    model_name='systemblueprintversion',
                    constraint=models.UniqueConstraint(fields=('blueprint', 'version'), name='uniq_blueprint_version'),
                ),
                migrations.AddConstraint(
                    model_name='tenantmodulestate',
                    constraint=models.UniqueConstraint(fields=('tenant', 'module_key'), name='uniq_tenant_module_state'),
                ),
                migrations.AddConstraint(
                    model_name='tenantuser',
                    constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='uniq_tenant_user'),
                ),
            ],
        ),
    ]
