# Generated by Django 6.0.5 on 2026-07-01 06:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from core_apps.blueprints.models import GenerationJob, SystemInstance


def _ensure_generation_fields(apps, schema_editor):
    connection = schema_editor.connection
    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            table_name: {column.name for column in connection.introspection.get_table_description(cursor, table_name)}
            for table_name in ("sys_instances", "sys_generation_jobs")
            if table_name in connection.introspection.table_names()
        }

    instance_field_names = ("artifact_checksum", "artifact_path", "current_generation_job", "instance_key", "published_at", "runtime_mode")
    generation_job_field_names = ("artifact_name", "artifact_path", "artifact_size", "config_snapshot_json", "created_at", "job_key", "job_logs_json", "job_stage", "requested_by", "retry_count")

    for field_name in instance_field_names:
        field = SystemInstance._meta.get_field(field_name)
        if field.column in existing_columns.get("sys_instances", set()):
            continue
        schema_editor.add_field(SystemInstance, field)

    for field_name in generation_job_field_names:
        field = GenerationJob._meta.get_field(field_name)
        if field.column in existing_columns.get("sys_generation_jobs", set()):
            continue
        schema_editor.add_field(GenerationJob, field)


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_tenant_systemblueprint_systemblueprintversion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_ensure_generation_fields, migrations.RunPython.noop),
                migrations.RunSQL(
                    sql="""
                    UPDATE sys_instances
                    SET runtime_mode = mode
                    WHERE runtime_mode IS NULL OR runtime_mode = '';
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="systeminstance",
                    name="artifact_checksum",
                    field=models.CharField(blank=True, max_length=128, verbose_name="产物校验码"),
                ),
                migrations.AddField(
                    model_name="systeminstance",
                    name="artifact_path",
                    field=models.CharField(blank=True, max_length=500, verbose_name="产物路径"),
                ),
                migrations.AddField(
                    model_name="systeminstance",
                    name="current_generation_job",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_for_instances",
                        to="system.generationjob",
                        verbose_name="当前生成任务",
                    ),
                ),
                migrations.AddField(
                    model_name="systeminstance",
                    name="instance_key",
                    field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name="实例标识"),
                ),
                migrations.AddField(
                    model_name="systeminstance",
                    name="published_at",
                    field=models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
                ),
                migrations.AddField(
                    model_name="systeminstance",
                    name="runtime_mode",
                    field=models.CharField(
                        choices=[("SAAS", "SaaS"), ("CODE_EXPORT", "代码导出")],
                        default="SAAS",
                        max_length=20,
                        verbose_name="运行模式",
                    ),
                ),
                migrations.AddField(
                    model_name="generationjob",
                    name="artifact_name",
                    field=models.CharField(blank=True, max_length=255, verbose_name="产物名称"),
                ),
                migrations.AddField(
                    model_name="generationjob",
                    name="artifact_path",
                    field=models.CharField(blank=True, max_length=500, verbose_name="产物路径"),
                ),
                migrations.AddField(
                    model_name="generationjob",
                    name="artifact_size",
                    field=models.BigIntegerField(default=0, verbose_name="产物大小"),
                ),
                migrations.AddField(
                    model_name="generationjob",
                    name="config_snapshot_json",
                    field=models.JSONField(blank=True, default=dict, verbose_name="配置快照"),
                ),
                migrations.AddField(
                    model_name="generationjob",
                    name="created_at",
                    field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间"),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name="generationjob",
                    name="job_key",
                    field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name="任务标识"),
                ),
                migrations.AddField(
                    model_name="generationjob",
                    name="job_logs_json",
                    field=models.JSONField(blank=True, default=list, verbose_name="任务日志"),
                ),
                migrations.AddField(
                    model_name="generationjob",
                    name="job_stage",
                    field=models.CharField(default="PENDING", max_length=50, verbose_name="任务阶段"),
                ),
                migrations.AddField(
                    model_name="generationjob",
                    name="requested_by",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发起人",
                    ),
                ),
                migrations.AddField(
                    model_name="generationjob",
                    name="retry_count",
                    field=models.PositiveIntegerField(default=0, verbose_name="重试次数"),
                ),
            ],
        ),
    ]
