# Generated by Django 6.0.5 on 2026-07-01 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_generation_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationjob",
            name="instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generation_jobs",
                to="system.systeminstance",
                verbose_name="实例",
            ),
        ),
    ]
