# Generated by Django 6.0.5 on 2026-07-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_generation_job_nullable_instance'),
        ('blueprints', '0002_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='generationjob',
                    name='blueprint_version',
                ),
                migrations.RemoveField(
                    model_name='generationjob',
                    name='instance',
                ),
                migrations.RemoveField(
                    model_name='generationjob',
                    name='requested_by',
                ),
                migrations.RemoveField(
                    model_name='systeminstance',
                    name='current_generation_job',
                ),
                migrations.RemoveField(
                    model_name='systemblueprint',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='systeminstance',
                    name='blueprint',
                ),
                migrations.RemoveConstraint(
                    model_name='systemblueprintversion',
                    name='uniq_blueprint_version',
                ),
                migrations.RemoveField(
                    model_name='systeminstance',
                    name='blueprint_version',
                ),
                migrations.RemoveField(
                    model_name='tenantconfigsnapshot',
                    name='blueprint_version',
                ),
                migrations.RemoveField(
                    model_name='systeminstance',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='systeminstance',
                    name='tenant',
                ),
                migrations.RemoveField(
                    model_name='tenantconfigsnapshot',
                    name='tenant',
                ),
                migrations.RemoveConstraint(
                    model_name='tenantmodulestate',
                    name='uniq_tenant_module_state',
                ),
                migrations.RemoveConstraint(
                    model_name='tenantuser',
                    name='uniq_tenant_user',
                ),
                migrations.DeleteModel(
                    name='GenerationJob',
                ),
                migrations.RemoveField(
                    model_name='systemblueprintversion',
                    name='blueprint',
                ),
                migrations.RemoveField(
                    model_name='systemblueprintversion',
                    name='created_by',
                ),
                migrations.DeleteModel(
                    name='SystemInstance',
                ),
                migrations.DeleteModel(
                    name='TenantConfigSnapshot',
                ),
                migrations.RemoveField(
                    model_name='tenantmodulestate',
                    name='tenant',
                ),
                migrations.RemoveField(
                    model_name='tenantuser',
                    name='tenant',
                ),
                migrations.RemoveField(
                    model_name='tenantuser',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='SystemBlueprint',
                ),
                migrations.DeleteModel(
                    name='SystemBlueprintVersion',
                ),
                migrations.DeleteModel(
                    name='TenantModuleState',
                ),
                migrations.DeleteModel(
                    name='Tenant',
                ),
                migrations.DeleteModel(
                    name='TenantUser',
                ),
            ],
        ),
    ]
