# Generated by Django 6.0.5 on 2026-07-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp_auth", "0002_erpdepartment_erpuser_dept"),
        ("system", "0005_remove_generationjob_blueprint_version_and_more"),
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationlog",
            name="erp_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operation_logs",
                to="erp_auth.erpuser",
                verbose_name="ERP用户",
            ),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_logs",
                to="tenant.tenant",
                verbose_name="租户",
            ),
        ),
    ]

