# Generated by Django 6.0.5 on 2026-06-29 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def migrate_completed_orders_to_closed(apps, schema_editor):
    SalesOrder = apps.get_model('sales', 'SalesOrder')
    SalesOrder.objects.filter(status='COMPLETED').update(status='CLOSED')


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorder_submitted_by_submitted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='invoiced_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_APPROVAL', '待审核'), ('APPROVED', '审核通过'), ('REJECTED', '已驳回'), ('ALLOCATED', '库存已锁定'), ('PARTIALLY_SHIPPED', '部分发货'), ('SHIPPED', '全部发货'), ('CLOSED', '已关闭'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20),
        ),
        migrations.RunPython(migrate_completed_orders_to_closed, migrations.RunPython.noop),
        migrations.CreateModel(
            name='SalesExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', '提交'), ('APPROVE', '审核通过'), ('REJECT', '审核驳回'), ('ALLOCATE', '锁库'), ('CREATE_OUTBOUND', '生成出库申请'), ('CLOSE', '关闭'), ('CANCEL', '取消')], max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(blank=True, max_length=20, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='sales.salesorder')),
            ],
            options={
                'verbose_name': '销售执行日志',
                'verbose_name_plural': '销售执行日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
