# Generated by Django 6.0.5 on 2026-07-03 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesorder_closed_at_and_more'),
        ('tenant', '0003_fix_missing_tenant_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderapprovallog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_approval_logs', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='orderattachment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_attachments', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='orderchangelog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_change_logs', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='salesexecutionlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_execution_logs', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_items', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='tenant.tenant'),
        ),
    ]
