# Generated by Django 6.0.5 on 2026-07-12 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_contact_created_at_alter_contact_customer_and_more'),
        ('erp_auth', '0002_erpdepartment_erpuser_dept'),
        ('inventory', '0010_alter_inventory_product_alter_inventory_tenant_and_more'),
        ('sales', '0006_alter_orderapprovallog_approved_by_and_more'),
        ('tenant', '0003_fix_missing_tenant_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderapprovallog',
            name='action',
            field=models.CharField(max_length=50, verbose_name='审核动作'),
        ),
        migrations.AlterField(
            model_name='orderapprovallog',
            name='approved_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='审核时间'),
        ),
        migrations.AlterField(
            model_name='orderapprovallog',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='orderapprovallog',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='审核意见'),
        ),
        migrations.AlterField(
            model_name='orderapprovallog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='sales.salesorder', verbose_name='销售订单'),
        ),
        migrations.AlterField(
            model_name='orderapprovallog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_approval_logs', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='orderattachment',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='orderattachment',
            name='file_url',
            field=models.CharField(max_length=500, verbose_name='文件地址'),
        ),
        migrations.AlterField(
            model_name='orderattachment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='sales.salesorder', verbose_name='销售订单'),
        ),
        migrations.AlterField(
            model_name='orderattachment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_attachments', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='orderattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='orderattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='上传人'),
        ),
        migrations.AlterField(
            model_name='orderchangelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='orderchangelog',
            name='field_name',
            field=models.CharField(max_length=50, verbose_name='变更字段'),
        ),
        migrations.AlterField(
            model_name='orderchangelog',
            name='new_value',
            field=models.TextField(blank=True, null=True, verbose_name='变更后'),
        ),
        migrations.AlterField(
            model_name='orderchangelog',
            name='old_value',
            field=models.TextField(blank=True, null=True, verbose_name='变更前'),
        ),
        migrations.AlterField(
            model_name='orderchangelog',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='orderchangelog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='sales.salesorder', verbose_name='销售订单'),
        ),
        migrations.AlterField(
            model_name='orderchangelog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_change_logs', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='salesexecutionlog',
            name='action',
            field=models.CharField(choices=[('SUBMIT', '提交'), ('APPROVE', '审核通过'), ('REJECT', '审核驳回'), ('ALLOCATE', '锁库'), ('CREATE_OUTBOUND', '生成出库申请'), ('CLOSE', '关闭'), ('CANCEL', '取消')], max_length=30, verbose_name='执行动作'),
        ),
        migrations.AlterField(
            model_name='salesexecutionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='salesexecutionlog',
            name='from_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='原状态'),
        ),
        migrations.AlterField(
            model_name='salesexecutionlog',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='salesexecutionlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='sales.salesorder', verbose_name='销售订单'),
        ),
        migrations.AlterField(
            model_name='salesexecutionlog',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='salesexecutionlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_execution_logs', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='salesexecutionlog',
            name='to_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='新状态'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='关闭时间'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to='erp_auth.erpuser', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='客户名称快照'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer_phone_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='客户电话快照'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='预计交付日期'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(auto_now_add=True, verbose_name='订单日期'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_APPROVAL', '待审核'), ('APPROVED', '审核通过'), ('REJECTED', '已驳回'), ('ALLOCATED', '库存已锁定'), ('PARTIALLY_SHIPPED', '部分发货'), ('SHIPPED', '全部发货'), ('CLOSED', '已关闭'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_sales_orders', to='erp_auth.erpuser', verbose_name='提交人'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='总金额'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='total_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='总数量'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='allocated_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='已分配数量'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='invoiced_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='已开票数量'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder', verbose_name='销售订单'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='product_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='商品名称快照'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='销售数量'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='shipped_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='已发货数量'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_items', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='仓库'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='sales.salesorder', verbose_name='销售订单'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='发货单号'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipped_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发货时间'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(default='SHIPPED', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.salesorderitem', verbose_name='销售订单明细'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='发货数量'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.shipment', verbose_name='发货单'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='tenant.tenant', verbose_name='租户'),
        ),
    ]
