# Generated by Django 6.0.5 on 2026-05-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='currency',
            field=models.CharField(default='CNY', max_length=10, verbose_name='常用币种'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.13, max_digits=5, verbose_name='默认税率'),
        ),
        migrations.AddField(
            model_name='supplierattachment',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='资质到期日'),
        ),
    ]
