# Generated by Django 6.0.5 on 2026-07-03 01:34

import django.db.models.deletion
from django.db import migrations, models


def clear_legacy_owner_refs(apps, schema_editor):
    Supplier = apps.get_model('supplier', 'Supplier')
    SupplierTransferLog = apps.get_model('supplier', 'SupplierTransferLog')
    Supplier.objects.exclude(owner_id__isnull=True).update(owner_id=None)
    SupplierTransferLog.objects.exclude(old_owner_id__isnull=True).update(old_owner_id=None)
    SupplierTransferLog.objects.exclude(new_owner_id__isnull=True).update(new_owner_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('erp_auth', '0001_initial'),
        ('supplier', '0003_supplier_settlement_defaults'),
    ]

    operations = [
        migrations.RunPython(clear_legacy_owner_refs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='supplier',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_suppliers', to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='suppliertransferlog',
            name='new_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sup_transferred_to', to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='suppliertransferlog',
            name='old_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sup_transferred_from', to='erp_auth.erpuser'),
        ),
    ]
