# Generated by Django 6.0.5 on 2026-07-03 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_alter_supplier_owner_and_more'),
        ('tenant', '0003_fix_missing_tenant_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='supplierattachment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_attachments', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_contacts', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='supplierevaluation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_evaluations', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='supplierfollowrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_follow_records', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='suppliertag',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_tags', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='suppliertransferlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_transfer_logs', to='tenant.tenant'),
        ),
    ]
