# Generated by Django 6.0.5 on 2026-07-03 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_auth', '0002_erpdepartment_erpuser_dept'),
        ('supplier', '0005_supplier_tenant_supplierattachment_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_suppliers', to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_suppliers', to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpdepartment'),
        ),
        migrations.AlterField(
            model_name='supplierattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='supplierevaluation',
            name='evaluated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='supplierfollowrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='suppliertransferlog',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser'),
        ),
    ]
