# Generated by Django 6.0.5 on 2026-07-12 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_auth', '0002_erpdepartment_erpuser_dept'),
        ('supplier', '0006_alter_supplier_created_by_alter_supplier_deleted_by_and_more'),
        ('tenant', '0003_fix_missing_tenant_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='account_holder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='账户名'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='银行账号'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='开户银行'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(default='China', max_length=100, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_suppliers', to='erp_auth.erpuser', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_suppliers', to='erp_auth.erpuser', verbose_name='删除人'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpdepartment', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所属行业'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_suppliers', to='erp_auth.erpuser', verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '激活'), ('INACTIVE', '未激活'), ('BLACKLIST', '黑名单')], default='ACTIVE', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_level',
            field=models.CharField(choices=[('A', 'A级'), ('B', 'B级'), ('C', 'C级'), ('D', 'D级')], default='C', max_length=10, verbose_name='供应商等级'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('MANUFACTURER', '制造商'), ('DISTRIBUTOR', '分销商'), ('SERVICE_PROVIDER', '服务商'), ('LOGISTICS', '物流商'), ('OTHER', '其他')], default='MANUFACTURER', max_length=20, verbose_name='供应商类型'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='网址'),
        ),
        migrations.AlterField(
            model_name='supplierattachment',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='supplierattachment',
            name='file_size',
            field=models.BigIntegerField(verbose_name='文件大小'),
        ),
        migrations.AlterField(
            model_name='supplierattachment',
            name='file_url',
            field=models.CharField(max_length=500, verbose_name='文件地址'),
        ),
        migrations.AlterField(
            model_name='supplierattachment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='supplier.supplier', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='supplierattachment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_attachments', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='supplierattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='supplierattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='上传人'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未知')], default='U', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='是否主要联系人'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='联系人姓名'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='supplier.supplier', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_contacts', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='wechat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='微信'),
        ),
        migrations.AlterField(
            model_name='supplierevaluation',
            name='delivery_score',
            field=models.IntegerField(default=5, verbose_name='交付评分'),
        ),
        migrations.AlterField(
            model_name='supplierevaluation',
            name='evaluated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评分时间'),
        ),
        migrations.AlterField(
            model_name='supplierevaluation',
            name='evaluated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='评分人'),
        ),
        migrations.AlterField(
            model_name='supplierevaluation',
            name='price_score',
            field=models.IntegerField(default=5, verbose_name='价格评分'),
        ),
        migrations.AlterField(
            model_name='supplierevaluation',
            name='quality_score',
            field=models.IntegerField(default=5, verbose_name='质量评分'),
        ),
        migrations.AlterField(
            model_name='supplierevaluation',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='supplierevaluation',
            name='service_score',
            field=models.IntegerField(default=5, verbose_name='服务评分'),
        ),
        migrations.AlterField(
            model_name='supplierevaluation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='supplier.supplier', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='supplierevaluation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_evaluations', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='supplierfollowrecord',
            name='content',
            field=models.TextField(verbose_name='跟进内容'),
        ),
        migrations.AlterField(
            model_name='supplierfollowrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='supplierfollowrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='supplierfollowrecord',
            name='follow_type',
            field=models.CharField(choices=[('PHONE', '电话'), ('VISIT', '拜访'), ('EMAIL', '邮件'), ('MEETING', '会议'), ('OTHER', '其他')], max_length=20, verbose_name='跟进方式'),
        ),
        migrations.AlterField(
            model_name='supplierfollowrecord',
            name='next_follow_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下次跟进时间'),
        ),
        migrations.AlterField(
            model_name='supplierfollowrecord',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_records', to='supplier.supplier', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='supplierfollowrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_follow_records', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='suppliertag',
            name='color',
            field=models.CharField(default='blue', max_length=20, verbose_name='标签颜色'),
        ),
        migrations.AlterField(
            model_name='suppliertag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='标签名称'),
        ),
        migrations.AlterField(
            model_name='suppliertag',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='suppliertag',
            name='suppliers',
            field=models.ManyToManyField(related_name='tags', to='supplier.supplier', verbose_name='关联供应商'),
        ),
        migrations.AlterField(
            model_name='suppliertag',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_tags', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='suppliertransferlog',
            name='new_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sup_transferred_to', to='erp_auth.erpuser', verbose_name='新负责人'),
        ),
        migrations.AlterField(
            model_name='suppliertransferlog',
            name='old_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sup_transferred_from', to='erp_auth.erpuser', verbose_name='原负责人'),
        ),
        migrations.AlterField(
            model_name='suppliertransferlog',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='suppliertransferlog',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='suppliertransferlog',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_logs', to='supplier.supplier', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='suppliertransferlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_transfer_logs', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='suppliertransferlog',
            name='transfer_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='转移时间'),
        ),
    ]
