from core_apps.modules.registry import ModuleDefinition


MODULE = ModuleDefinition(
    key="ap_payable",
    label="应付管理",
    django_app="business_apps.ap_payable",
    api_prefix="api/ap-payable/",
    depends_on=("supplier", "purchase", "finance", "platform"),
    menus=(
        {
            "code": "ap",
            "name": "应付管理",
            "path": "/ap",
            "icon": "WalletOutlined",
            "order": 1100,
        },
        {
            "code": "ap:account",
            "name": "应付账款",
            "parent": "ap",
            "path": "/ap/accounts",
            "component": "apPayable/APList",
            "icon": "ProfileOutlined",
            "order": 1101,
        },
        {
            "code": "ap:payment",
            "name": "付款单",
            "parent": "ap",
            "path": "/ap/payments",
            "component": "apPayable/PaymentList",
            "icon": "CreditCardOutlined",
            "order": 1102,
        },
        {
            "code": "ap:refund",
            "name": "供应商退款单",
            "parent": "ap",
            "path": "/ap/refunds",
            "component": "apPayable/RefundList",
            "icon": "ImportOutlined",
            "order": 1103,
        },
        {
            "code": "ap:summary",
            "name": "供应商汇总",
            "parent": "ap",
            "path": "/ap/summary",
            "component": "apPayable/SupplierSummary",
            "icon": "GroupOutlined",
            "order": 1104,
        },
        {
            "code": "ap:aging",
            "name": "账龄分析",
            "parent": "ap",
            "path": "/ap/aging",
            "component": "apPayable/AgingAnalysis",
            "icon": "BarChartOutlined",
            "order": 1105,
        },
        {
            "code": "ap:allocate",
            "name": "付款核销",
            "parent": "ap",
            "path": "/ap/allocate",
            "component": "apPayable/AllocationPage",
            "order": 1106,
            "hide_in_menu": True,
            "status": True,
        },
    ),
    permissions=(
        {"code": "ap:account:view", "name": "查看应付账款", "parent": "ap:account"},
        {"code": "ap:account:update", "name": "编辑应付账款", "parent": "ap:account"},
        {"code": "ap:payment:view", "name": "查看付款单", "parent": "ap:payment"},
        {"code": "ap:payment:create", "name": "新建付款单", "parent": "ap:payment"},
        {"code": "ap:payment:update", "name": "编辑付款单", "parent": "ap:payment"},
        {"code": "ap:payment:submit", "name": "提交付款审核", "parent": "ap:payment"},
        {"code": "ap:payment:approve", "name": "审核支付", "parent": "ap:payment"},
        {"code": "ap:payment:execute", "name": "执行付款单", "parent": "ap:payment"},
        {"code": "ap:payment:cancel", "name": "取消付款单", "parent": "ap:payment"},
        {"code": "ap:payment:delete", "name": "作废付款单", "parent": "ap:payment"},
        {"code": "ap:refund:view", "name": "查看供应商退款单", "parent": "ap:refund"},
        {"code": "ap:refund:create", "name": "新建供应商退款单", "parent": "ap:refund"},
        {"code": "ap:refund:update", "name": "编辑供应商退款单", "parent": "ap:refund"},
        {"code": "ap:refund:delete", "name": "删除供应商退款单", "parent": "ap:refund"},
        {"code": "ap:refund:submit", "name": "提交供应商退款单审核", "parent": "ap:refund"},
        {"code": "ap:refund:approve", "name": "审核供应商退款单", "parent": "ap:refund"},
        {"code": "ap:refund:execute", "name": "执行供应商退款单", "parent": "ap:refund"},
        {"code": "ap:allocation:view", "name": "查看付款核销", "parent": "ap"},
        {"code": "ap:allocation:create", "name": "创建付款核销", "parent": "ap"},
        {"code": "ap:allocation:update", "name": "编辑付款核销", "parent": "ap"},
        {"code": "ap:allocation:delete", "name": "删除付款核销", "parent": "ap"},
    ),
    features=("应付台账", "付款单", "供应商退款单", "核销", "供应商对账", "AP 看板"),
    workflows=("采购入库自动生成应付", "付款执行与核销", "采购退货生成供应商退款单"),
    field_rules=("付款动作受现金账户配置影响",),
    default_rules=("付款执行后允许同步财务流水与会计过账",),
    public_services=("business_apps.ap_payable.services.APService",),
    export_metadata={
        "export_enabled": True,
        "must_export_with": ("supplier", "purchase", "finance", "platform"),
        "has_frontend_pages": True,
        "seed_data": {"required": False, "keys": ()},
        "attachments_dependency": False,
        "task_log_dependency": True,
    },
)
