# Generated by Django 6.0.5 on 2026-06-15 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 文件中心
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_ext', models.CharField(blank=True, max_length=20, verbose_name='文件扩展名')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME类型')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('storage_type', models.CharField(choices=[('LOCAL', '本地存储'), ('MINIO', 'MinIO'), ('S3', 'Amazon S3')], default='LOCAL', max_length=10, verbose_name='存储类型')),
                ('bucket', models.CharField(blank=True, max_length=100, verbose_name='存储桶')),
                ('object_key', models.CharField(blank=True, max_length=500, verbose_name='对象键')),
                ('file_url', models.CharField(max_length=500, verbose_name='文件访问URL')),
                ('md5', models.CharField(blank=True, max_length=32, verbose_name='MD5校验')),
                ('module', models.CharField(choices=[('customer', '客户'), ('supplier', '供应商'), ('product', '商品'), ('purchase', '采购'), ('sales', '销售'), ('inventory', '库存'), ('supply_chain', '供应链'), ('report', '报表'), ('system', '系统')], max_length=20, verbose_name='所属模块')),
                ('business_type', models.CharField(max_length=50, verbose_name='业务类型')),
                ('business_id', models.IntegerField(verbose_name='业务ID')),
                ('access_level', models.CharField(choices=[('PUBLIC', '公开'), ('LOGIN', '登录可见'), ('BUSINESS', '业务权限继承')], default='BUSINESS', max_length=10, verbose_name='访问级别')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={'verbose_name': '文件', 'verbose_name_plural': '文件', 'ordering': ['-uploaded_at']},
        ),
        migrations.AddIndex(model_name='file', index=models.Index(fields=['module', 'business_type', 'business_id'], name='idx_file_business')),
        migrations.AddIndex(model_name='file', index=models.Index(fields=['md5'], name='idx_file_md5')),
        migrations.AddIndex(model_name='file', index=models.Index(fields=['uploaded_by'], name='idx_file_uploader')),
        migrations.AddIndex(model_name='file', index=models.Index(fields=['storage_type'], name='idx_file_storage')),

        # 字典分类
        migrations.CreateModel(
            name='DictType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_code', models.CharField(max_length=50, unique=True, verbose_name='字典编码')),
                ('dict_name', models.CharField(max_length=100, verbose_name='字典名称')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('status', models.CharField(choices=[('ACTIVE', '启用'), ('DISABLED', '禁用')], default='ACTIVE', max_length=10, verbose_name='状态')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={'verbose_name': '字典分类', 'verbose_name_plural': '字典分类', 'ordering': ['sort', 'id'], 'db_table': 'sys_dict_types'},
        ),

        # 字典项
        migrations.CreateModel(
            name='DictItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, verbose_name='字典项编码')),
                ('item_name', models.CharField(max_length=100, verbose_name='字典项名称')),
                ('item_value', models.CharField(blank=True, max_length=200, verbose_name='字典项值')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='颜色标记')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(choices=[('ACTIVE', '启用'), ('DISABLED', '禁用')], default='ACTIVE', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dict_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='platform.dicttype', verbose_name='字典分类')),
            ],
            options={'verbose_name': '字典项', 'verbose_name_plural': '字典项', 'ordering': ['sort', 'id'], 'db_table': 'sys_dict_items', 'unique_together': {('dict_type', 'item_code')}},
        ),
        migrations.AddIndex(model_name='dictitem', index=models.Index(fields=['dict_type', 'status'], name='idx_dict_item_type_status')),

        # 编码规则
        migrations.CreateModel(
            name='CodeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=50, unique=True, verbose_name='规则编码')),
                ('rule_name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('prefix', models.CharField(max_length=10, verbose_name='前缀')),
                ('date_format', models.CharField(default='%Y%m%d', max_length=20, verbose_name='日期格式')),
                ('sequence_length', models.IntegerField(default=4, verbose_name='流水号位数')),
                ('current_sequence', models.IntegerField(default=0, verbose_name='当前序号')),
                ('current_date_key', models.CharField(blank=True, default='', max_length=20, verbose_name='当前日期键')),
                ('reset_type', models.CharField(choices=[('NEVER', '永不重置'), ('YEAR', '按年重置'), ('MONTH', '按月重置'), ('DAY', '按日重置')], default='DAY', max_length=10, verbose_name='重置策略')),
                ('status', models.CharField(choices=[('ACTIVE', '启用'), ('DISABLED', '禁用')], default='ACTIVE', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={'verbose_name': '编码规则', 'verbose_name_plural': '编码规则', 'ordering': ['rule_code'], 'db_table': 'code_rules'},
        ),
        migrations.AddIndex(model_name='coderule', index=models.Index(fields=['rule_code'], name='idx_code_rule_code')),
    ]
