# Generated by Django 6.0.5 on 2026-06-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderule',
            name='current_date_key',
            field=models.CharField(blank=True, default='', help_text='用于判断是否需要重置序号', max_length=20, verbose_name='当前日期键'),
        ),
        migrations.AlterField(
            model_name='coderule',
            name='date_format',
            field=models.CharField(default='%Y%m%d', help_text='如: %Y%m%d, %Y%m, 留空则不含日期', max_length=20, verbose_name='日期格式'),
        ),
        migrations.AlterField(
            model_name='coderule',
            name='prefix',
            field=models.CharField(help_text='如: SO, PO, CUS', max_length=10, verbose_name='前缀'),
        ),
        migrations.AlterField(
            model_name='coderule',
            name='rule_code',
            field=models.CharField(help_text='如: SALES_ORDER, PURCHASE_ORDER', max_length=50, unique=True, verbose_name='规则编码'),
        ),
        migrations.AlterField(
            model_name='dictitem',
            name='item_value',
            field=models.CharField(blank=True, help_text='可选，用于存储额外数据', max_length=200, verbose_name='字典项值'),
        ),
        migrations.AlterField(
            model_name='file',
            name='business_type',
            field=models.CharField(help_text='如: purchase_order, sales_order, customer', max_length=50, verbose_name='业务类型'),
        ),
    ]
