# Generated by Django 6.0.5 on 2026-07-03 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_auth', '0002_erpdepartment_erpuser_dept'),
        ('platform', '0003_purge_legacy_null_tenant_business_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='dicttype',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='上传人'),
        ),
    ]
