from core_apps.modules.registry import ModuleDefinition


MODULE = ModuleDefinition(
    key="reports",
    label="报表中心",
    django_app="business_apps.reports",
    api_prefix="api/reports/",
    depends_on=("crm", "supplier", "inventory", "sales", "purchase", "supply_chain"),
    menus=(
        {
            "code": "reports",
            "name": "报表中心",
            "path": "/reports",
            "icon": "BarChartOutlined",
            "order": 800,
        },
        {
            "code": "reports:dashboard",
            "name": "经营驾驶舱",
            "parent": "reports",
            "path": "/reports/dashboard",
            "component": "reports/Dashboard",
            "icon": "DashboardOutlined",
            "order": 801,
        },
        {
            "code": "reports:sales",
            "name": "销售分析",
            "parent": "reports",
            "path": "/reports/sales",
            "component": "reports/SalesAnalysis",
            "icon": "RiseOutlined",
            "order": 802,
        },
        {
            "code": "reports:purchase",
            "name": "采购分析",
            "parent": "reports",
            "path": "/reports/purchase",
            "component": "reports/PurchaseAnalysis",
            "icon": "FallOutlined",
            "order": 803,
        },
        {
            "code": "reports:inventory",
            "name": "库存分析",
            "parent": "reports",
            "path": "/reports/inventory",
            "component": "reports/InventoryAnalysis",
            "icon": "InboxOutlined",
            "order": 804,
        },
        {
            "code": "reports:customer",
            "name": "客户分析",
            "parent": "reports",
            "path": "/reports/customer",
            "component": "reports/CustomerAnalysis",
            "icon": "TeamOutlined",
            "order": 805,
        },
        {
            "code": "reports:supplier",
            "name": "供应商分析",
            "parent": "reports",
            "path": "/reports/supplier",
            "component": "reports/SupplierAnalysis",
            "icon": "ShopOutlined",
            "order": 806,
        },
        {
            "code": "reports:product",
            "name": "商品分析",
            "parent": "reports",
            "path": "/reports/product",
            "component": "reports/ProductAnalysis",
            "icon": "ShoppingOutlined",
            "order": 807,
        },
        {
            "code": "reports:export",
            "name": "自定义导出",
            "parent": "reports",
            "path": "/reports/export",
            "component": "reports/ExportList",
            "icon": "DownloadOutlined",
            "order": 808,
        },
    ),
    permissions=(
        {"code": "reports:dashboard:view", "name": "查看驾驶舱", "parent": "reports:dashboard"},
        {"code": "reports:sales:view", "name": "查看销售分析", "parent": "reports:sales"},
        {"code": "reports:purchase:view", "name": "查看采购分析", "parent": "reports:purchase"},
        {"code": "reports:inventory:view", "name": "查看库存分析", "parent": "reports:inventory"},
        {"code": "reports:customer:view", "name": "查看客户分析", "parent": "reports:customer"},
        {"code": "reports:supplier:view", "name": "查看供应商分析", "parent": "reports:supplier"},
        {"code": "reports:product:view", "name": "查看商品分析", "parent": "reports:product"},
        {"code": "reports:export:view", "name": "查看导出", "parent": "reports:export"},
        {"code": "reports:export:create", "name": "创建导出", "parent": "reports:export"},
    ),
    features=("经营驾驶舱", "销售分析", "采购分析", "库存分析", "客户分析", "供应商分析", "商品分析", "导出中心"),
    workflows=("多业务域报表聚合", "报表异步导出"),
    field_rules=("报表模块只读，按主题组织 API 子路径",),
    default_rules=("报表服务聚合销售、采购、库存、客户、供应商数据",),
    public_services=("business_apps.reports.services.ReportService",),
    export_metadata={
        "export_enabled": True,
        "must_export_with": ("crm", "supplier", "inventory", "sales", "purchase", "supply_chain"),
        "feature_pruning": {
            "dashboard": {"code_prunable": False, "ui_prunable": False, "config_only": True},
            "sales_analysis": {"code_prunable": False, "ui_prunable": False, "config_only": True},
            "purchase_analysis": {"code_prunable": False, "ui_prunable": False, "config_only": True},
            "inventory_analysis": {"code_prunable": False, "ui_prunable": False, "config_only": True},
            "customer_analysis": {"code_prunable": False, "ui_prunable": False, "config_only": True},
            "supplier_analysis": {"code_prunable": False, "ui_prunable": False, "config_only": True},
            "product_analysis": {"code_prunable": False, "ui_prunable": False, "config_only": True},
            "export_center": {"code_prunable": False, "ui_prunable": False, "config_only": True},
        },
        "frontend_feature_pages": {
            "dashboard": ("/reports/dashboard",),
            "sales_analysis": ("/reports/sales",),
            "purchase_analysis": ("/reports/purchase",),
            "inventory_analysis": ("/reports/inventory",),
            "customer_analysis": ("/reports/customer",),
            "supplier_analysis": ("/reports/supplier",),
            "product_analysis": ("/reports/product",),
            "export_center": ("/reports/export",),
        },
        "has_frontend_pages": True,
        "seed_data": {"required": False, "keys": ()},
        "attachments_dependency": False,
        "task_log_dependency": True,
    },
)
