# Generated by Django 6.0.5 on 2026-05-30 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_stock',
            field=models.DecimalField(decimal_places=3, default=999999, max_digits=15, verbose_name='最高库存'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='最低库存'),
        ),
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocktake_no', models.CharField(max_length=50, unique=True, verbose_name='盘点单号')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('IN_PROGRESS', '盘点中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stocktakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '库存盘点',
                'verbose_name_plural': '库存盘点',
            },
        ),
        migrations.CreateModel(
            name='StocktakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='系统数量')),
                ('actual_qty', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='实盘数量')),
                ('remark', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktake')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(max_length=50, unique=True, verbose_name='仓库编码')),
                ('warehouse_name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('type', models.CharField(choices=[('MAIN', '主仓库'), ('BRANCH', '分仓'), ('TEMPORARY', '临时仓')], default='MAIN', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
            },
        ),
        migrations.AddField(
            model_name='stocktake',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=50, unique=True, verbose_name='流水号')),
                ('transaction_type', models.CharField(choices=[('PURCHASE_IN', '采购入库'), ('SALE_OUT', '销售出库'), ('MANUAL_ADJUST', '手动调整'), ('STOCKTAKE_GAIN', '盘盈入库'), ('STOCKTAKE_LOSS', '盘亏出库'), ('TRANSFER_IN', '调拨入库'), ('TRANSFER_OUT', '调拨出库'), ('RETURN_IN', '退货入库'), ('RETURN_OUT', '退货出库')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='变动数量')),
                ('before_qty', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='变动前库存')),
                ('after_qty', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='变动后库存')),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='关联单据类型')),
                ('reference_id', models.IntegerField(blank=True, null=True, verbose_name='关联单据ID')),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'verbose_name': '库存流水',
                'verbose_name_plural': '库存流水',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='当前库存')),
                ('locked_qty', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='锁定库存')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': '库存主表',
                'verbose_name_plural': '库存主表',
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
