# Generated by Django 6.0.5 on 2026-06-29 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorytransaction_business_date_direction_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='business_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='业务日期'),
        ),
    ]
