# Generated by Django 6.0.5 on 2026-07-03 01:34

import django.db.models.deletion
from django.db import migrations, models


def clear_legacy_manager_refs(apps, schema_editor):
    Warehouse = apps.get_model('inventory', 'Warehouse')
    Warehouse.objects.exclude(manager_id__isnull=True).update(manager_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('erp_auth', '0001_initial'),
        ('inventory', '0005_alter_inventorytransaction_operator'),
    ]

    operations = [
        migrations.RunPython(clear_legacy_manager_refs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='warehouse',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='负责人'),
        ),
    ]
