# Generated by Django 6.0.5 on 2026-07-03 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_warehouse_manager'),
        ('tenant', '0003_fix_missing_tenant_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='productattachment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_attachments', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocktakes', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocktake_items', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='unit',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='tenant.tenant'),
        ),
    ]
