from core_apps.modules.registry import ModuleDefinition


MODULE = ModuleDefinition(
    key="accounting",
    label="总账会计",
    django_app="business_apps.accounting",
    api_prefix="api/accounting/",
    depends_on=("platform", "finance", "ar_receivable", "ap_payable"),
    menus=(
        {
            "code": "accounting",
            "name": "总账会计",
            "parent": "finance",
            "path": "/accounting",
            "icon": "BookOutlined",
            "order": 1210,
        },
        {
            "code": "accounting:subject",
            "name": "会计科目",
            "parent": "accounting",
            "path": "/accounting/subjects",
            "component": "accounting/SubjectList",
            "icon": "ProfileOutlined",
            "order": 1211,
        },
        {
            "code": "accounting:period",
            "name": "会计期间",
            "parent": "accounting",
            "path": "/accounting/periods",
            "component": "accounting/PeriodList",
            "icon": "CalendarOutlined",
            "order": 1212,
        },
        {
            "code": "accounting:voucher",
            "name": "凭证列表",
            "parent": "accounting",
            "path": "/accounting/vouchers",
            "component": "accounting/VoucherList",
            "icon": "FileTextOutlined",
            "order": 1213,
        },
        {
            "code": "accounting:posting_log",
            "name": "业务过账日志",
            "parent": "accounting",
            "path": "/accounting/posting-logs",
            "component": "accounting/PostingLogList",
            "icon": "NodeIndexOutlined",
            "order": 1214,
        },
    ),
    permissions=(
        {"code": "accounting:period:view", "name": "查看会计期间", "parent": "finance"},
        {"code": "accounting:period:create", "name": "创建会计期间", "parent": "finance"},
        {"code": "accounting:voucher:view", "name": "查看会计凭证", "parent": "finance"},
        {"code": "accounting:period:delete", "name": "删除会计期间", "parent": "finance"},
        {"code": "accounting:period:close", "name": "关闭会计期间", "parent": "finance"},
        {"code": "accounting:period:open", "name": "打开会计期间", "parent": "finance"},
        {"code": "accounting:period:update", "name": "维护会计期间", "parent": "finance"},
        {"code": "accounting:posting_log:view", "name": "查看业务过账日志", "parent": "finance"},
        {"code": "accounting:subject:view", "name": "查看会计科目", "parent": "finance"},
        {"code": "accounting:subject:create", "name": "创建会计科目", "parent": "finance"},
        {"code": "accounting:subject:delete", "name": "删除会计科目", "parent": "finance"},
        {"code": "accounting:subject:update", "name": "维护会计科目", "parent": "finance"},
    ),
    features=("会计科目", "会计期间", "凭证", "业务过账日志"),
    workflows=("业务单据过账总账",),
    field_rules=("凭证号默认依赖平台编码规则",),
    default_rules=("AR/AP/供应链执行完成后可触发会计过账",),
    public_services=("business_apps.accounting.services.PostingService",),
    export_metadata={
        "export_enabled": True,
        "must_export_with": ("platform", "finance", "ar_receivable", "ap_payable"),
        "has_frontend_pages": True,
        "seed_data": {"required": True, "keys": ("subjects", "periods")},
        "attachments_dependency": False,
        "task_log_dependency": True,
    },
)
