from core_apps.modules.registry import ModuleDefinition


MODULE = ModuleDefinition(
    key="sales",
    label="销售管理",
    django_app="business_apps.sales",
    api_prefix="api/sales/",
    depends_on=("crm", "inventory", "platform"),
    menus=(
        {
            "code": "sales",
            "name": "销售管理",
            "path": "/sales",
            "icon": "ShoppingOutlined",
            "order": 400,
        },
        {
            "code": "sales:order",
            "name": "销售订单",
            "parent": "sales",
            "path": "/sales/orders",
            "component": "sales/OrderList",
            "icon": "OrderedListOutlined",
            "order": 401,
        },
        {
            "code": "sales:stats",
            "name": "销售统计",
            "parent": "sales",
            "path": "/sales/stats",
            "component": "sales/SalesStats",
            "icon": "BarChartOutlined",
            "order": 402,
        },
        {
            "code": "sales:order:detail",
            "name": "订单详情",
            "parent": "sales",
            "path": "/sales/orders/:id",
            "component": "sales/OrderDetail",
            "order": 403,
            "status": True,
            "hide_in_menu": True,
        },
        {
            "code": "sales:order:new",
            "name": "新增订单",
            "parent": "sales",
            "path": "/sales/orders/new",
            "component": "sales/OrderForm",
            "order": 404,
            "status": True,
            "hide_in_menu": True,
        },
        {
            "code": "sales:order:edit",
            "name": "编辑订单",
            "parent": "sales",
            "path": "/sales/orders/:id/edit",
            "component": "sales/OrderForm",
            "order": 405,
            "status": True,
            "hide_in_menu": True,
        },
    ),
    permissions=(
        {"code": "sales:order:view", "name": "查看订单", "parent": "sales:order"},
        {"code": "sales:order:create", "name": "创建订单", "parent": "sales:order"},
        {"code": "sales:order:update", "name": "编辑订单", "parent": "sales:order"},
        {"code": "sales:order:delete", "name": "删除订单", "parent": "sales:order"},
        {"code": "sales:order:approve", "name": "审核订单", "parent": "sales:order"},
        {"code": "sales:order:allocate", "name": "锁定库存", "parent": "sales:order"},
        {"code": "sales:order:ship", "name": "订单发货", "parent": "sales:order"},
        {"code": "sales:order:cancel", "name": "取消订单", "parent": "sales:order"},
        {"code": "sales:order:close", "name": "关闭订单", "parent": "sales:order"},
    ),
    features=("销售订单", "销售统计"),
    workflows=("销售下单审批", "销售单驱动出库"),
    field_rules=("订单编辑页为隐藏路由",),
    default_rules=("销售单号默认复用平台编码规则",),
    public_services=("business_apps.sales.services.SalesOrderService",),
    export_metadata={
        "always_include": False,
        "export_enabled": True,
        "export_requires": ("crm", "inventory", "platform"),
        "must_export_with": ("crm", "inventory"),
        "feature_pruning": {
            "approval": {
                "code_prunable": False,
                "ui_prunable": True,
                "permission_codes": ("sales:order:approve",),
            },
            "credit_control": {"code_prunable": False, "ui_prunable": False, "config_only": True},
        },
        "frontend_feature_pages": {
            "approval": ("/sales/orders", "/sales/orders/:id"),
        },
        "seed_data": {"required": False, "keys": ()},
        "attachments_dependency": False,
        "task_log_dependency": True,
    },
)
