from core_apps.modules.registry import ModuleDefinition


MODULE = ModuleDefinition(
    key="system",
    label="系统管理",
    django_app="core_apps.system",
    api_prefix="api/system/",
    depends_on=(),
    menus=(
        {
            "code": "system",
            "name": "系统管理",
            "path": "/system",
            "icon": "SettingOutlined",
            "order": 100,
        },
        {
            "code": "system:user",
            "name": "用户管理",
            "parent": "system",
            "path": "/system/users",
            "component": "system/UserList",
            "icon": "UserOutlined",
            "order": 101,
        },
        {
            "code": "system:dept",
            "name": "部门管理",
            "parent": "system",
            "path": "/system/depts",
            "component": "system/DeptList",
            "icon": "ApartmentOutlined",
            "order": 102,
        },
        {
            "code": "system:role",
            "name": "角色管理",
            "parent": "system",
            "path": "/system/roles",
            "component": "system/RoleList",
            "icon": "TeamOutlined",
            "order": 103,
        },
        {
            "code": "system:perm",
            "name": "权限管理",
            "parent": "system",
            "path": "/system/perms",
            "component": "system/PermissionList",
            "icon": "SafetyOutlined",
            "order": 104,
        },
        {
            "code": "system:log",
            "name": "操作日志",
            "parent": "system",
            "path": "/system/logs",
            "component": "system/LogList",
            "icon": "HistoryOutlined",
            "order": 105,
        },
    ),
    permissions=(
        {"code": "user:create", "name": "新增用户", "parent": "system:user"},
        {"code": "user:update", "name": "编辑用户", "parent": "system:user"},
        {"code": "user:delete", "name": "删除用户", "parent": "system:user"},
    ),
    features=("用户管理", "部门管理", "角色管理", "权限管理", "操作日志"),
    workflows=("角色授权", "菜单与按钮权限维护"),
    field_rules=(),
    default_rules=(),
    public_services=(),
)
