# Generated by Django 6.0.5 on 2026-06-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='purchaseapprovallog',
            new_name='purchase_pu_purchas_38a19d_idx',
            old_name='purchase_approval_po_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseattachment',
            new_name='purchase_pu_purchas_09a1a5_idx',
            old_name='purchase_attach_po_idx',
        ),
        migrations.RenameIndex(
            model_name='purchasechangelog',
            new_name='purchase_pu_purchas_34eb87_idx',
            old_name='purchase_change_po_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='purchase_pu_purchas_b57a23_idx',
            old_name='purchase_no_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='purchase_pu_supplie_92a52c_idx',
            old_name='purchase_supplier_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='purchase_pu_status_92210d_idx',
            old_name='purchase_status_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='purchase_pu_created_db3ad7_idx',
            old_name='purchase_created_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='purchase_pu_order_d_f38a57_idx',
            old_name='purchase_date_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorder',
            new_name='purchase_pu_dept_id_f5d74d_idx',
            old_name='purchase_dept_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorderitem',
            new_name='purchase_pu_purchas_4cc84c_idx',
            old_name='purchase_item_po_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseorderitem',
            new_name='purchase_pu_product_d41ee0_idx',
            old_name='purchase_item_prod_idx',
        ),
        migrations.RenameIndex(
            model_name='purchasereceipt',
            new_name='purchase_pu_receipt_5f5d2c_idx',
            old_name='purchase_receipt_no_idx',
        ),
        migrations.RenameIndex(
            model_name='purchasereceipt',
            new_name='purchase_pu_purchas_0bf5a0_idx',
            old_name='purchase_receipt_po_idx',
        ),
        migrations.RenameIndex(
            model_name='purchasereceipt',
            new_name='purchase_pu_status_dbd757_idx',
            old_name='purchase_receipt_status_idx',
        ),
        migrations.RenameIndex(
            model_name='purchasereceiptitem',
            new_name='purchase_pu_receipt_2db301_idx',
            old_name='purchase_ri_receipt_idx',
        ),
    ]
