# Generated by Django 6.0.5 on 2026-06-29 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchaseorder_submitted_by_submitted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='关闭时间'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='已退货数量'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消时间'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_purchase_receipts', to=settings.AUTH_USER_MODEL, verbose_name='执行人'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_APPROVAL', '待审核'), ('APPROVED', '审核通过'), ('REJECTED', '已驳回'), ('PARTIALLY_RECEIVED', '部分到货'), ('RECEIVED', '全部到货'), ('CLOSED', '已关闭'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态'),
        ),
    ]
