# Generated by Django 6.0.5 on 2026-07-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchaseorder_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseapprovallog',
            name='action',
            field=models.CharField(choices=[('AUTO_APPROVE', '自动审核通过'), ('APPROVE', '审核通过'), ('REJECT', '审核驳回')], max_length=50, verbose_name='审核动作'),
        ),
    ]
