# Generated by Django 6.0.5 on 2026-07-03 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_alter_purchaseapprovallog_action'),
        ('tenant', '0003_fix_missing_tenant_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseapprovallog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_approval_logs', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='purchasechangelog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_change_logs', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_receipts', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='purchasereceiptitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_receipt_items', to='tenant.tenant'),
        ),
    ]
