from core_apps.modules.registry import ModuleDefinition


MODULE = ModuleDefinition(
    key="crm",
    label="客户管理",
    django_app="business_apps.crm",
    api_prefix="api/crm/",
    depends_on=("platform",),
    menus=(
        {
            "code": "crm",
            "name": "客户管理",
            "path": "/crm",
            "icon": "UsergroupAddOutlined",
            "order": 200,
        },
        {
            "code": "crm:customer",
            "name": "客户列表",
            "parent": "crm",
            "path": "/crm/customers",
            "component": "crm/CustomerList",
            "icon": "TeamOutlined",
            "order": 201,
        },
        {
            "code": "crm:customer:detail",
            "name": "客户详情",
            "parent": "crm",
            "path": "/crm/customers/:id",
            "component": "crm/CustomerDetail",
            "order": 202,
            "status": True,
            "hide_in_menu": True,
        },
        {
            "code": "crm:customer:new",
            "name": "新增客户",
            "parent": "crm",
            "path": "/crm/customers/new",
            "component": "crm/CustomerForm",
            "order": 203,
            "status": True,
            "hide_in_menu": True,
        },
        {
            "code": "crm:customer:edit",
            "name": "编辑客户",
            "parent": "crm",
            "path": "/crm/customers/:id/edit",
            "component": "crm/CustomerForm",
            "order": 204,
            "status": True,
            "hide_in_menu": True,
        },
    ),
    permissions=(
        {"code": "crm:customer:view", "name": "查看客户", "parent": "crm:customer"},
        {"code": "crm:customer:create", "name": "创建客户", "parent": "crm:customer"},
        {"code": "crm:customer:update", "name": "编辑客户", "parent": "crm:customer"},
        {"code": "crm:customer:delete", "name": "删除客户", "parent": "crm:customer"},
        {"code": "crm:customer:transfer", "name": "转移客户", "parent": "crm:customer"},
    ),
    features=("客户档案", "联系人", "跟进记录", "标签与附件"),
    workflows=("客户建档", "客户详情与编辑隐藏路由"),
    field_rules=("客户详情、新增、编辑页均依赖菜单入口 + 按钮权限",),
    default_rules=("客户编码默认复用平台编码规则",),
    public_services=("business_apps.crm.services.CustomerCreditService",),
    export_metadata={
        "export_enabled": True,
        "must_export_with": ("platform",),
        "has_frontend_pages": True,
        "seed_data": {"required": False, "keys": ()},
        "attachments_dependency": True,
        "task_log_dependency": False,
    },
)
