# Generated by Django 6.0.5 on 2026-07-01 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='SystemBlueprint',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('key', models.CharField(max_length=100, unique=True, verbose_name='蓝图标识')),
                        ('name', models.CharField(max_length=100, verbose_name='蓝图名称')),
                        ('description', models.TextField(blank=True, verbose_name='描述')),
                        ('industry', models.CharField(blank=True, max_length=100, verbose_name='行业')),
                        ('status', models.CharField(choices=[('DRAFT', '草稿'), ('ACTIVE', '启用'), ('ARCHIVED', '归档')], default='DRAFT', max_length=20, verbose_name='状态')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blueprints', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                    ],
                    options={
                        'verbose_name': '系统蓝图',
                        'verbose_name_plural': '系统蓝图',
                        'db_table': 'sys_blueprints',
                        'ordering': ['name', 'id'],
                    },
                ),
                migrations.CreateModel(
                    name='SystemBlueprintVersion',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('version', models.CharField(max_length=50, verbose_name='版本号')),
                        ('config_json', models.JSONField(blank=True, default=dict, verbose_name='配置快照')),
                        ('change_note', models.CharField(blank=True, max_length=500, verbose_name='变更说明')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                        ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                        ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='blueprints.systemblueprint', verbose_name='蓝图')),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blueprint_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                    ],
                    options={
                        'verbose_name': '蓝图版本',
                        'verbose_name_plural': '蓝图版本',
                        'db_table': 'sys_blueprint_versions',
                        'ordering': ['-created_at', '-id'],
                    },
                ),
                migrations.CreateModel(
                    name='GenerationJob',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('job_key', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='任务标识')),
                        ('job_type', models.CharField(choices=[('CREATE_SAAS', '创建 SaaS'), ('EXPORT_CODE', '导出代码')], max_length=20, verbose_name='任务类型')),
                        ('job_stage', models.CharField(default='PENDING', max_length=50, verbose_name='任务阶段')),
                        ('status', models.CharField(choices=[('PENDING', '待执行'), ('RUNNING', '执行中'), ('SUCCEEDED', '成功'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='状态')),
                        ('payload_json', models.JSONField(blank=True, default=dict, verbose_name='输入参数')),
                        ('config_snapshot_json', models.JSONField(blank=True, default=dict, verbose_name='配置快照')),
                        ('result_json', models.JSONField(blank=True, default=dict, verbose_name='输出结果')),
                        ('job_logs_json', models.JSONField(blank=True, default=list, verbose_name='任务日志')),
                        ('artifact_path', models.CharField(blank=True, max_length=500, verbose_name='产物路径')),
                        ('artifact_name', models.CharField(blank=True, max_length=255, verbose_name='产物名称')),
                        ('artifact_size', models.BigIntegerField(default=0, verbose_name='产物大小')),
                        ('retry_count', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                        ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                        ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                        ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                        ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_generation_jobs', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                        ('blueprint_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_jobs', to='blueprints.systemblueprintversion', verbose_name='蓝图版本')),
                    ],
                    options={
                        'verbose_name': '生成任务',
                        'verbose_name_plural': '生成任务',
                        'db_table': 'sys_generation_jobs',
                        'ordering': ['-id'],
                    },
                ),
                migrations.CreateModel(
                    name='SystemInstance',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('instance_key', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='实例标识')),
                        ('name', models.CharField(max_length=100, verbose_name='实例名称')),
                        ('mode', models.CharField(choices=[('SAAS', 'SaaS'), ('CODE_EXPORT', '代码导出')], max_length=20, verbose_name='模式')),
                        ('runtime_mode', models.CharField(choices=[('SAAS', 'SaaS'), ('CODE_EXPORT', '代码导出')], default='SAAS', max_length=20, verbose_name='运行模式')),
                        ('status', models.CharField(choices=[('DRAFT', '草稿'), ('GENERATING', '生成中'), ('ACTIVE', '可用'), ('FAILED', '失败'), ('ARCHIVED', '归档')], default='DRAFT', max_length=20, verbose_name='状态')),
                        ('artifact_path', models.CharField(blank=True, max_length=500, verbose_name='产物路径')),
                        ('artifact_checksum', models.CharField(blank=True, max_length=128, verbose_name='产物校验码')),
                        ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                        ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='blueprints.systemblueprint', verbose_name='蓝图')),
                        ('blueprint_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='blueprints.systemblueprintversion', verbose_name='蓝图版本')),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_system_instances', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                        ('current_generation_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_instances', to='blueprints.generationjob', verbose_name='当前生成任务')),
                    ],
                    options={
                        'verbose_name': '系统实例',
                        'verbose_name_plural': '系统实例',
                        'db_table': 'sys_instances',
                        'ordering': ['-created_at', '-id'],
                    },
                ),
            ],
        ),
    ]
