# Generated by Django 6.0.5 on 2026-07-01 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blueprints', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='systeminstance',
                    name='tenant',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='tenant.tenant', verbose_name='租户'),
                ),
                migrations.AddField(
                    model_name='generationjob',
                    name='instance',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='blueprints.systeminstance', verbose_name='实例'),
                ),
                migrations.AddConstraint(
                    model_name='systemblueprintversion',
                    constraint=models.UniqueConstraint(fields=('blueprint', 'version'), name='uniq_blueprint_version'),
                ),
            ],
        ),
    ]
