# Generated by Django 6.0.5 on 2026-07-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminstance',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('GENERATING', '生成中'), ('ACTIVE', '可用'), ('INACTIVE', '停用'), ('FAILED', '失败'), ('ARCHIVED', '归档')], default='DRAFT', max_length=20, verbose_name='状态'),
        ),
    ]
