# Generated by Django 6.0.5 on 2026-07-01 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blueprints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Tenant',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(max_length=100, unique=True, verbose_name='租户编码')),
                        ('name', models.CharField(max_length=100, verbose_name='租户名称')),
                        ('status', models.CharField(choices=[('ACTIVE', '启用'), ('INACTIVE', '停用'), ('ARCHIVED', '归档')], default='ACTIVE', max_length=20, verbose_name='状态')),
                        ('industry', models.CharField(blank=True, max_length=100, verbose_name='行业')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                    ],
                    options={
                        'verbose_name': '租户',
                        'verbose_name_plural': '租户',
                        'db_table': 'sys_tenants',
                        'ordering': ['name', 'id'],
                    },
                ),
                migrations.CreateModel(
                    name='TenantConfigSnapshot',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('config_json', models.JSONField(blank=True, default=dict, verbose_name='配置快照')),
                        ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='应用时间')),
                        ('blueprint_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_snapshots', to='blueprints.systemblueprintversion', verbose_name='蓝图版本')),
                        ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_snapshots', to='tenant.tenant', verbose_name='租户')),
                    ],
                    options={
                        'verbose_name': '租户配置快照',
                        'verbose_name_plural': '租户配置快照',
                        'db_table': 'sys_tenant_config_snapshots',
                        'ordering': ['-applied_at', '-id'],
                    },
                ),
                migrations.CreateModel(
                    name='TenantModuleState',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('module_key', models.CharField(max_length=100, verbose_name='模块标识')),
                        ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                        ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_states', to='tenant.tenant', verbose_name='租户')),
                    ],
                    options={
                        'verbose_name': '租户模块开关',
                        'verbose_name_plural': '租户模块开关',
                        'db_table': 'sys_tenant_module_states',
                        'ordering': ['tenant_id', 'module_key'],
                        'constraints': [models.UniqueConstraint(fields=('tenant', 'module_key'), name='uniq_tenant_module_state')],
                    },
                ),
                migrations.CreateModel(
                    name='TenantUser',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('is_owner', models.BooleanField(default=False, verbose_name='是否所有者')),
                        ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                        ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenant.tenant', verbose_name='租户')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                    ],
                    options={
                        'verbose_name': '租户成员',
                        'verbose_name_plural': '租户成员',
                        'db_table': 'sys_tenant_users',
                        'ordering': ['tenant_id', 'user_id', 'id'],
                        'constraints': [models.UniqueConstraint(fields=('tenant', 'user'), name='uniq_tenant_user')],
                    },
                ),
            ],
        ),
    ]
