# Generated by Django 6.0.5 on 2026-07-02 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0003_alter_systeminstance_status'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='tenant',
                    name='instance',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='blueprints.systeminstance', verbose_name='绑定实例'),
                ),
                migrations.AddField(
                    model_name='tenant',
                    name='user_limit',
                    field=models.PositiveIntegerField(blank=True, null=True, verbose_name='用户数上限'),
                ),
            ],
        ),
    ]
