from core_apps.modules.registry import ModuleDefinition


MODULE = ModuleDefinition(
    key="ar_receivable",
    label="应收管理",
    django_app="business_apps.ar_receivable",
    api_prefix="api/ar-receivable/",
    depends_on=("crm", "sales", "supply_chain", "finance"),
    menus=(
        {
            "code": "ar",
            "name": "财务应收",
            "path": "/ar-receivable",
            "icon": "AccountBookOutlined",
            "order": 1000,
            "status": True,
            "hide_in_menu": False,
        },
        {
            "code": "ar:receivable",
            "name": "应收账款",
            "parent": "ar",
            "path": "/ar-receivable/list",
            "component": "arReceivable/ReceivableList",
            "icon": "FileTextOutlined",
            "order": 1001,
        },
        {
            "code": "ar:receipt",
            "name": "收款单",
            "parent": "ar",
            "path": "/ar-receivable/receipts",
            "component": "arReceivable/ReceiptList",
            "icon": "MoneyCollectOutlined",
            "order": 1002,
        },
        {
            "code": "ar:aging",
            "name": "账龄分析",
            "parent": "ar",
            "path": "/ar-receivable/aging",
            "component": "arReceivable/AgingAnalysis",
            "icon": "LineChartOutlined",
            "order": 1003,
        },
    ),
    permissions=(
        {"code": "ar:receivable:view", "name": "查看应收账款", "parent": "ar:receivable"},
        {"code": "ar:receivable:update", "name": "编辑应收账款", "parent": "ar:receivable"},
        {"code": "ar:receivable:generate", "name": "生成应收账款", "parent": "ar:receivable"},
        {"code": "ar:receipt:view", "name": "查看收款单", "parent": "ar:receipt"},
        {"code": "ar:receipt:create", "name": "新建收款单", "parent": "ar:receipt"},
        {"code": "ar:receipt:update", "name": "编辑收款单", "parent": "ar:receipt"},
        {"code": "ar:receipt:delete", "name": "删除收款单", "parent": "ar:receipt"},
        {"code": "ar:receipt:approve", "name": "审核收款单", "parent": "ar:receipt"},
        {"code": "ar:receipt:execute", "name": "执行收款单", "parent": "ar:receipt"},
        {"code": "ar:receipt:write_off", "name": "收款单核销", "parent": "ar:receipt"},
    ),
    features=("应收台账", "收款单", "账龄分析"),
    workflows=("出库完成自动生成应收", "收款执行与核销"),
    field_rules=("收款动作受现金账户配置影响",),
    default_rules=("收款执行后允许同步财务流水与会计过账",),
    public_services=("business_apps.ar_receivable.services.ARService",),
    export_metadata={
        "export_enabled": True,
        "must_export_with": ("crm", "sales", "supply_chain", "finance"),
        "has_frontend_pages": True,
        "seed_data": {"required": False, "keys": ()},
        "attachments_dependency": False,
        "task_log_dependency": True,
    },
)
