# Generated by Django 6.0.5 on 2026-07-02 12:13

import core_apps.erp_auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='权限标识')),
                ('type', models.CharField(choices=[('MENU', '菜单'), ('BUTTON', '按钮')], default='MENU', max_length=10, verbose_name='权限类型')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, max_length=200, null=True, verbose_name='组件路径')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('hide_in_menu', models.BooleanField(default=False, verbose_name='在菜单中隐藏')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='erp_auth.erppermission')),
            ],
            options={
                'verbose_name': 'ERP 权限',
                'verbose_name_plural': 'ERP 权限',
                'db_table': 'erp_permissions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ERPRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('code', models.CharField(max_length=50, verbose_name='角色标识')),
                ('data_scope', models.CharField(choices=[('ALL', '全部数据'), ('SELF', '仅本人数据'), ('DEPARTMENT', '本部门数据')], default='SELF', max_length=20, verbose_name='数据权限范围')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('is_system', models.BooleanField(default=False, verbose_name='是否系统角色')),
                ('permissions', models.ManyToManyField(blank=True, to='erp_auth.erppermission', verbose_name='功能权限')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_roles', to='tenant.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': 'ERP 角色',
                'verbose_name_plural': 'ERP 角色',
                'db_table': 'erp_roles',
                'ordering': ['tenant_id', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ERPUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('status', models.BooleanField(default=True, verbose_name='用户状态')),
                ('is_super_admin', models.BooleanField(default=False, verbose_name='是否租户超级管理员')),
                ('must_change_password', models.BooleanField(default=True, verbose_name='是否首次改密')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最近登录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='erp_auth.erprole', verbose_name='拥有角色')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_users', to='tenant.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': 'ERP 用户',
                'verbose_name_plural': 'ERP 用户',
                'db_table': 'erp_users',
                'ordering': ['tenant_id', 'username', 'id'],
            },
            managers=[
                ('objects', core_apps.erp_auth.models.ERPUserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='erprole',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_erp_role_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='erpuser',
            constraint=models.UniqueConstraint(fields=('tenant', 'username'), name='uniq_erp_username_per_tenant'),
        ),
    ]
