from core_apps.modules.registry import ModuleDefinition


MODULE = ModuleDefinition(
    key="finance",
    label="资金与财务分析",
    django_app="business_apps.finance",
    api_prefix="api/finance/",
    depends_on=("crm", "supplier"),
    menus=(
        {
            "code": "finance",
            "name": "财务分析",
            "path": "/finance",
            "icon": "PieChartOutlined",
            "order": 1200,
        },
        {
            "code": "finance:dashboard",
            "name": "财务大盘",
            "parent": "finance",
            "path": "/finance/dashboard",
            "component": "finance/Dashboard",
            "icon": "DashboardOutlined",
            "order": 1201,
        },
        {
            "code": "finance:recon",
            "name": "对账中心",
            "parent": "finance",
            "path": "/finance/reconciliation",
            "component": "finance/ReconciliationCenter",
            "icon": "AuditOutlined",
            "order": 1202,
        },
        {
            "code": "finance:cash",
            "name": "现金账户",
            "parent": "finance",
            "path": "/finance/cash-accounts",
            "component": "finance/CashAccountList",
            "icon": "BankOutlined",
            "order": 1203,
        },
    ),
    permissions=(
        {"code": "finance:dashboard:view", "name": "查看财务看板", "parent": "finance"},
        {"code": "finance:aging:view", "name": "查看账龄分析", "parent": "finance"},
        {"code": "finance:reconciliation:customer:view", "name": "查看客户对账", "parent": "finance"},
        {"code": "finance:reconciliation:supplier:view", "name": "查看供应商对账", "parent": "finance"},
        {"code": "finance:cash:reference", "name": "引用资金账户", "parent": "finance:cash"},
        {"code": "finance:cash:view", "name": "查看资金账户", "parent": "finance"},
        {"code": "finance:cash:create", "name": "新建资金账户", "parent": "finance"},
        {"code": "finance:cash:update", "name": "编辑资金账户", "parent": "finance"},
        {"code": "finance:export_task:view", "name": "查看导出任务", "parent": "finance"},
        {"code": "finance:export_task:create", "name": "创建导出任务", "parent": "finance"},
        {"code": "finance:export_task:update", "name": "更新导出任务", "parent": "finance"},
        {"code": "finance:export_task:delete", "name": "删除导出任务", "parent": "finance"},
    ),
    features=("财务看板", "账龄分析", "客户对账", "供应商对账", "资金账户"),
    workflows=("收付款与资金流水汇总",),
    field_rules=("资金账户为应收应付执行动作的前置条件",),
    default_rules=("财务汇总服务会聚合 AR/AP 业务数据",),
    public_services=("business_apps.finance.services.FinanceAnalyticsService",),
    export_metadata={
        "export_enabled": True,
        "must_export_with": ("crm", "supplier"),
        "has_frontend_pages": True,
        "seed_data": {"required": True, "keys": ("cash_accounts",)},
        "attachments_dependency": False,
        "task_log_dependency": True,
    },
)
