from core_apps.modules.registry import ModuleDefinition


MODULE = ModuleDefinition(
    key="inventory",
    label="库存管理",
    django_app="business_apps.inventory",
    api_prefix="api/inventory/",
    depends_on=("platform",),
    menus=(
        {
            "code": "inventory",
            "name": "库存管理",
            "path": "/inventory",
            "icon": "InboxOutlined",
            "order": 300,
        },
        {
            "code": "inventory:category",
            "name": "商品分类",
            "parent": "inventory",
            "path": "/inventory/categories",
            "component": "inventory/CategoryList",
            "icon": "BarsOutlined",
            "order": 301,
        },
        {
            "code": "inventory:unit",
            "name": "计量单位",
            "parent": "inventory",
            "path": "/inventory/units",
            "component": "inventory/UnitList",
            "icon": "FontSizeOutlined",
            "order": 302,
        },
        {
            "code": "inventory:product",
            "name": "商品管理",
            "parent": "inventory",
            "path": "/inventory/products",
            "component": "inventory/ProductList",
            "icon": "ShoppingOutlined",
            "order": 303,
        },
        {
            "code": "inventory:product:detail",
            "name": "商品详情",
            "parent": "inventory",
            "path": "/inventory/products/:id",
            "component": "inventory/ProductDetail",
            "order": 304,
            "status": True,
            "hide_in_menu": True,
        },
        {
            "code": "inventory:product:new",
            "name": "新增商品",
            "parent": "inventory",
            "path": "/inventory/products/new",
            "component": "inventory/ProductForm",
            "order": 305,
            "status": True,
            "hide_in_menu": True,
        },
        {
            "code": "inventory:product:edit",
            "name": "编辑商品",
            "parent": "inventory",
            "path": "/inventory/products/:id/edit",
            "component": "inventory/ProductForm",
            "order": 306,
            "status": True,
            "hide_in_menu": True,
        },
        {
            "code": "inventory:warehouse",
            "name": "仓库管理",
            "parent": "inventory",
            "path": "/inventory/warehouses",
            "component": "inventory/WarehouseList",
            "icon": "HomeOutlined",
            "order": 307,
        },
        {
            "code": "inventory:query",
            "name": "库存查询",
            "parent": "inventory",
            "path": "/inventory/query",
            "component": "inventory/InventoryList",
            "icon": "MonitorOutlined",
            "order": 308,
        },
        {
            "code": "inventory:transaction",
            "name": "库存流水",
            "parent": "inventory",
            "path": "/inventory/transactions",
            "component": "inventory/TransactionList",
            "icon": "HistoryOutlined",
            "order": 309,
        },
        {
            "code": "inventory:stocktake",
            "name": "库存盘点",
            "parent": "inventory",
            "path": "/inventory/stocktake",
            "component": "inventory/StocktakeList",
            "icon": "CheckSquareOutlined",
            "order": 310,
        },
        {
            "code": "inventory:stocktake:detail",
            "name": "盘点单详情",
            "parent": "inventory",
            "path": "/inventory/stocktake/:id",
            "component": "inventory/StocktakeDetail",
            "order": 311,
            "status": True,
            "hide_in_menu": True,
        },
    ),
    permissions=(
        {"code": "inventory:category:reference", "name": "引用商品分类", "parent": "inventory:category"},
        {"code": "inventory:category:view", "name": "查看商品分类", "parent": "inventory:category"},
        {"code": "inventory:category:create", "name": "创建商品分类", "parent": "inventory:category"},
        {"code": "inventory:category:update", "name": "编辑商品分类", "parent": "inventory:category"},
        {"code": "inventory:category:delete", "name": "删除商品分类", "parent": "inventory:category"},
        {"code": "inventory:unit:reference", "name": "引用计量单位", "parent": "inventory:unit"},
        {"code": "inventory:unit:view", "name": "查看计量单位", "parent": "inventory:unit"},
        {"code": "inventory:unit:create", "name": "创建计量单位", "parent": "inventory:unit"},
        {"code": "inventory:unit:update", "name": "编辑计量单位", "parent": "inventory:unit"},
        {"code": "inventory:unit:delete", "name": "删除计量单位", "parent": "inventory:unit"},
        {"code": "inventory:product:reference", "name": "引用商品", "parent": "inventory:product"},
        {"code": "inventory:product:view", "name": "查看商品", "parent": "inventory:product"},
        {"code": "inventory:product:create", "name": "创建商品", "parent": "inventory:product"},
        {"code": "inventory:product:update", "name": "编辑商品", "parent": "inventory:product"},
        {"code": "inventory:product:delete", "name": "删除商品", "parent": "inventory:product"},
        {"code": "inventory:product:export", "name": "导出商品", "parent": "inventory:product"},
        {"code": "inventory:product:import", "name": "导入商品", "parent": "inventory:product"},
        {"code": "inventory:warehouse:reference", "name": "引用仓库", "parent": "inventory:warehouse"},
        {"code": "inventory:warehouse:view", "name": "查看仓库", "parent": "inventory:warehouse"},
        {"code": "inventory:warehouse:create", "name": "创建仓库", "parent": "inventory:warehouse"},
        {"code": "inventory:warehouse:update", "name": "编辑仓库", "parent": "inventory:warehouse"},
        {"code": "inventory:warehouse:delete", "name": "删除仓库", "parent": "inventory:warehouse"},
        {"code": "inventory:inventory:view", "name": "查看库存", "parent": "inventory:query"},
        {"code": "inventory:inventory:reference", "name": "引用库存", "parent": "inventory:query"},
        {"code": "inventory:inventory:adjust", "name": "手工调整库存", "parent": "inventory:query"},
        {"code": "inventory:stocktake:view", "name": "查看盘点单", "parent": "inventory:stocktake"},
        {"code": "inventory:stocktake:create", "name": "创建盘点单", "parent": "inventory:stocktake"},
        {"code": "inventory:stocktake:update", "name": "编辑盘点单", "parent": "inventory:stocktake"},
        {"code": "inventory:stocktake:approve", "name": "审核盘点单", "parent": "inventory:stocktake"},
        {"code": "inventory:stocktake:complete", "name": "完成盘点", "parent": "inventory:stocktake"},
        {"code": "inventory:stocktake:delete", "name": "删除盘点单", "parent": "inventory:stocktake"},
    ),
    features=("商品主数据", "仓库与库存台账", "库存流水", "库存盘点"),
    workflows=("商品建档", "库存盘点闭环"),
    field_rules=("库存流水统一落 business_date", "盘点详情页为隐藏路由",),
    default_rules=("商品编码、分类等基础资料可复用平台编码规则",),
    public_services=("business_apps.inventory.services.InventoryService", "business_apps.inventory.services.UnitService"),
    export_metadata={
        "always_include": False,
        "export_enabled": True,
        "export_requires": ("platform",),
        "feature_pruning": {
            "multi_warehouse": {"code_prunable": False, "ui_prunable": False, "config_only": True},
            "batch_tracking": {"code_prunable": False, "ui_prunable": False, "config_only": True},
            "serial_number": {"code_prunable": False, "ui_prunable": False, "config_only": True},
            "stocktake": {
                "code_prunable": True,
                "ui_prunable": True,
                "frontend_pages": ("/inventory/stocktake", "/inventory/stocktake/:id"),
            },
        },
        "frontend_feature_pages": {
            "stocktake": ("/inventory/stocktake", "/inventory/stocktake/:id"),
        },
        "seed_data": {
            "required": True,
            "keys": ("units", "product_categories", "warehouses"),
        },
        "attachments_dependency": False,
        "task_log_dependency": False,
    },
)
