from core_apps.modules.registry import ModuleDefinition


MODULE = ModuleDefinition(
    key="supplier",
    label="供应商管理",
    django_app="business_apps.supplier",
    api_prefix="api/supplier/",
    depends_on=("platform",),
    menus=(
        {
            "code": "supplier",
            "name": "供应商管理",
            "path": "/supplier",
            "icon": "ShopOutlined",
            "order": 500,
        },
        {
            "code": "supplier:supplier",
            "name": "供应商列表",
            "parent": "supplier",
            "path": "/supplier/suppliers",
            "component": "supplier/SupplierList",
            "icon": "TeamOutlined",
            "order": 501,
        },
        {
            "code": "supplier:supplier:detail",
            "name": "供应商详情",
            "parent": "supplier",
            "path": "/supplier/suppliers/:id",
            "component": "supplier/SupplierDetail",
            "order": 502,
            "status": True,
            "hide_in_menu": True,
        },
        {
            "code": "supplier:supplier:new",
            "name": "新增供应商",
            "parent": "supplier",
            "path": "/supplier/suppliers/new",
            "component": "supplier/SupplierForm",
            "order": 503,
            "status": True,
            "hide_in_menu": True,
        },
        {
            "code": "supplier:supplier:edit",
            "name": "编辑供应商",
            "parent": "supplier",
            "path": "/supplier/suppliers/:id/edit",
            "component": "supplier/SupplierForm",
            "order": 504,
            "status": True,
            "hide_in_menu": True,
        },
    ),
    permissions=(
        {"code": "supplier:supplier:view", "name": "查看供应商", "parent": "supplier:supplier"},
        {"code": "supplier:supplier:create", "name": "创建供应商", "parent": "supplier:supplier"},
        {"code": "supplier:supplier:update", "name": "编辑供应商", "parent": "supplier:supplier"},
        {"code": "supplier:supplier:delete", "name": "删除供应商", "parent": "supplier:supplier"},
        {"code": "supplier:supplier:transfer", "name": "转移供应商", "parent": "supplier:supplier"},
    ),
    features=("供应商档案", "联系人", "跟进记录", "评估管理"),
    workflows=("供应商建档", "供应商详情与编辑隐藏路由"),
    field_rules=("供应商结算默认值由模块服务维护",),
    default_rules=("供应商编码默认复用平台编码规则",),
    public_services=("business_apps.supplier.services.SupplierSettlementService",),
    export_metadata={
        "export_enabled": True,
        "must_export_with": ("platform",),
        "has_frontend_pages": True,
        "seed_data": {"required": False, "keys": ()},
        "attachments_dependency": True,
        "task_log_dependency": False,
    },
)
