# Generated by Django 6.0.5 on 2026-07-03 01:34

import django.db.models.deletion
from django.db import migrations, models


def clear_legacy_owner_refs(apps, schema_editor):
    Customer = apps.get_model('crm', 'Customer')
    TransferLog = apps.get_model('crm', 'TransferLog')
    Customer.objects.exclude(owner_id__isnull=True).update(owner_id=None)
    TransferLog.objects.exclude(old_owner_id__isnull=True).update(old_owner_id=None)
    TransferLog.objects.exclude(new_owner_id__isnull=True).update(new_owner_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_credit_policy_fields'),
        ('erp_auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_legacy_owner_refs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_customers', to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='transferlog',
            name='new_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_to', to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='transferlog',
            name='old_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_from', to='erp_auth.erpuser'),
        ),
    ]
