# Generated by Django 6.0.5 on 2026-07-03 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_customer_owner_alter_transferlog_new_owner_and_more'),
        ('tenant', '0003_fix_missing_tenant_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_contacts', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='customerattachment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_attachments', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='customertag',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_tags', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='followrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_follow_records', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='transferlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_transfer_logs', to='tenant.tenant'),
        ),
    ]
