# Generated by Django 6.0.5 on 2026-07-12 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_customer_created_by_alter_customer_deleted_by_and_more'),
        ('erp_auth', '0002_erpdepartment_erpuser_dept'),
        ('tenant', '0003_fix_missing_tenant_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='crm.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未知')], default='U', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='是否主要联系人'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='联系人姓名'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_contacts', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='wechat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='微信'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(default='China', max_length=100, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to='erp_auth.erpuser', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_level',
            field=models.CharField(choices=[('A', 'A级'), ('B', 'B级'), ('C', 'C级'), ('D', 'D级')], default='C', max_length=10, verbose_name='客户等级'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('PERSONAL', '个人'), ('COMPANY', '公司')], default='COMPANY', max_length=20, verbose_name='客户类型'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_customers', to='erp_auth.erpuser', verbose_name='删除人'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpdepartment', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所属行业'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_customers', to='erp_auth.erpuser', verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '激活'), ('INACTIVE', '未激活'), ('BLACKLIST', '黑名单')], default='ACTIVE', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='网址'),
        ),
        migrations.AlterField(
            model_name='customerattachment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='customerattachment',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='customerattachment',
            name='file_size',
            field=models.BigIntegerField(verbose_name='文件大小'),
        ),
        migrations.AlterField(
            model_name='customerattachment',
            name='file_url',
            field=models.CharField(max_length=500, verbose_name='文件地址'),
        ),
        migrations.AlterField(
            model_name='customerattachment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_attachments', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='customerattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='customerattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='上传人'),
        ),
        migrations.AlterField(
            model_name='customertag',
            name='color',
            field=models.CharField(default='blue', max_length=20, verbose_name='标签颜色'),
        ),
        migrations.AlterField(
            model_name='customertag',
            name='customers',
            field=models.ManyToManyField(related_name='tags', to='crm.customer', verbose_name='关联客户'),
        ),
        migrations.AlterField(
            model_name='customertag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='标签名称'),
        ),
        migrations.AlterField(
            model_name='customertag',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='customertag',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_tags', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='followrecord',
            name='content',
            field=models.TextField(verbose_name='跟进内容'),
        ),
        migrations.AlterField(
            model_name='followrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='followrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='followrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_records', to='crm.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='followrecord',
            name='follow_type',
            field=models.CharField(choices=[('PHONE', '电话'), ('VISIT', '拜访'), ('WECHAT', '微信'), ('EMAIL', '邮件'), ('MEETING', '会议'), ('OTHER', '其他')], max_length=20, verbose_name='跟进方式'),
        ),
        migrations.AlterField(
            model_name='followrecord',
            name='next_follow_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下次跟进时间'),
        ),
        migrations.AlterField(
            model_name='followrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_follow_records', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='transferlog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_logs', to='crm.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='transferlog',
            name='new_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_to', to='erp_auth.erpuser', verbose_name='新负责人'),
        ),
        migrations.AlterField(
            model_name='transferlog',
            name='old_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_from', to='erp_auth.erpuser', verbose_name='原负责人'),
        ),
        migrations.AlterField(
            model_name='transferlog',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='transferlog',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='transferlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_transfer_logs', to='tenant.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='transferlog',
            name='transfer_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='转移时间'),
        ),
    ]
