# Generated by Django 6.0.5 on 2026-05-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='hide_in_menu',
            field=models.BooleanField(default=False, verbose_name='在菜单中隐藏'),
        ),
    ]
