from core_apps.modules.registry import ModuleDefinition


MODULE = ModuleDefinition(
    key="supply_chain",
    label="供应链执行",
    django_app="business_apps.supply_chain",
    api_prefix="api/supply-chain/",
    depends_on=("crm", "supplier", "inventory", "sales", "purchase", "platform"),
    menus=(
        {
            "code": "supply_chain",
            "name": "供应链执行",
            "path": "/supply-chain",
            "icon": "ApartmentOutlined",
            "order": 700,
        },
        {
            "code": "supply_chain:outbound",
            "name": "销售出库",
            "parent": "supply_chain",
            "path": "/supply-chain/outbound",
            "component": "supplyChain/OutboundList",
            "icon": "ExportOutlined",
            "order": 701,
        },
        {
            "code": "supply_chain:outbound:detail",
            "name": "出库单详情",
            "parent": "supply_chain",
            "path": "/supply-chain/outbound/:id",
            "component": "supplyChain/OutboundDetail",
            "order": 702,
            "status": True,
            "hide_in_menu": True,
        },
        {
            "code": "supply_chain:transfer",
            "name": "仓库调拨",
            "parent": "supply_chain",
            "path": "/supply-chain/transfer",
            "component": "supplyChain/TransferList",
            "icon": "SwapOutlined",
            "order": 703,
        },
        {
            "code": "supply_chain:transfer:detail",
            "name": "调拨单详情",
            "parent": "supply_chain",
            "path": "/supply-chain/transfer/:id",
            "component": "supplyChain/TransferDetail",
            "order": 704,
            "status": True,
            "hide_in_menu": True,
        },
        {
            "code": "supply_chain:sales_return",
            "name": "销售退货",
            "parent": "supply_chain",
            "path": "/supply-chain/sales-return",
            "component": "supplyChain/SalesReturnList",
            "icon": "RollbackOutlined",
            "order": 705,
        },
        {
            "code": "supply_chain:sales_return:detail",
            "name": "销售退货单详情",
            "parent": "supply_chain",
            "path": "/supply-chain/sales-return/:id",
            "component": "supplyChain/SalesReturnDetail",
            "order": 706,
            "status": True,
            "hide_in_menu": True,
        },
        {
            "code": "supply_chain:purchase_return",
            "name": "采购退货",
            "parent": "supply_chain",
            "path": "/supply-chain/purchase-return",
            "component": "supplyChain/PurchaseReturnList",
            "icon": "UndoOutlined",
            "order": 707,
        },
        {
            "code": "supply_chain:purchase_return:detail",
            "name": "采购退货单详情",
            "parent": "supply_chain",
            "path": "/supply-chain/purchase-return/:id",
            "component": "supplyChain/PurchaseReturnDetail",
            "order": 708,
            "status": True,
            "hide_in_menu": True,
        },
        {
            "code": "supply_chain:alert",
            "name": "库存预警",
            "parent": "supply_chain",
            "path": "/supply-chain/alerts",
            "component": "supplyChain/AlertList",
            "icon": "AlertOutlined",
            "order": 709,
        },
        {
            "code": "supply_chain:trace",
            "name": "库存追溯",
            "parent": "supply_chain",
            "path": "/supply-chain/trace",
            "component": "supplyChain/TraceList",
            "icon": "AuditOutlined",
            "order": 710,
        },
    ),
    permissions=(
        {"code": "supply_chain:outbound:view", "name": "查看出库单", "parent": "supply_chain:outbound"},
        {"code": "supply_chain:outbound:create", "name": "创建出库单", "parent": "supply_chain:outbound"},
        {"code": "supply_chain:outbound:update", "name": "编辑出库单", "parent": "supply_chain:outbound"},
        {"code": "supply_chain:outbound:approve", "name": "审核出库单", "parent": "supply_chain:outbound"},
        {"code": "supply_chain:outbound:delete", "name": "删除出库单", "parent": "supply_chain:outbound"},
        {"code": "supply_chain:outbound:complete", "name": "执行出库", "parent": "supply_chain:outbound"},
        {"code": "supply_chain:outbound:cancel", "name": "取消出库单", "parent": "supply_chain:outbound"},
        {"code": "supply_chain:transfer:view", "name": "查看调拨单", "parent": "supply_chain:transfer"},
        {"code": "supply_chain:transfer:create", "name": "创建调拨单", "parent": "supply_chain:transfer"},
        {"code": "supply_chain:transfer:submit", "name": "提交审核", "parent": "supply_chain:transfer"},
        {"code": "supply_chain:transfer:update", "name": "编辑调拨单", "parent": "supply_chain:transfer"},
        {"code": "supply_chain:transfer:delete", "name": "删除调拨单", "parent": "supply_chain:transfer"},
        {"code": "supply_chain:transfer:approve", "name": "审核调拨单", "parent": "supply_chain:transfer"},
        {"code": "supply_chain:transfer:start", "name": "调出确认", "parent": "supply_chain:transfer"},
        {"code": "supply_chain:transfer:complete", "name": "调入确认", "parent": "supply_chain:transfer"},
        {"code": "supply_chain:transfer:cancel", "name": "取消调拨单", "parent": "supply_chain:transfer"},
        {"code": "supply_chain:sales_return:view", "name": "查看退货单", "parent": "supply_chain:sales_return"},
        {"code": "supply_chain:sales_return:create", "name": "创建退货单", "parent": "supply_chain:sales_return"},
        {"code": "supply_chain:sales_return:submit", "name": "提交退货单审核", "parent": "supply_chain:sales_return"},
        {"code": "supply_chain:sales_return:update", "name": "编辑退货单", "parent": "supply_chain:sales_return"},
        {"code": "supply_chain:sales_return:delete", "name": "删除退货单", "parent": "supply_chain:sales_return"},
        {"code": "supply_chain:sales_return:approve", "name": "审核退货单", "parent": "supply_chain:sales_return"},
        {"code": "supply_chain:sales_return:complete", "name": "完成退货", "parent": "supply_chain:sales_return"},
        {"code": "supply_chain:sales_return:cancel", "name": "取消退货单", "parent": "supply_chain:sales_return"},
        {"code": "supply_chain:purchase_return:view", "name": "查看退货单", "parent": "supply_chain:purchase_return"},
        {"code": "supply_chain:purchase_return:create", "name": "创建退货单", "parent": "supply_chain:purchase_return"},
        {"code": "supply_chain:purchase_return:submit", "name": "提交退货单审核", "parent": "supply_chain:purchase_return"},
        {"code": "supply_chain:purchase_return:update", "name": "编辑退货单", "parent": "supply_chain:purchase_return"},
        {"code": "supply_chain:purchase_return:delete", "name": "删除退货单", "parent": "supply_chain:purchase_return"},
        {"code": "supply_chain:purchase_return:approve", "name": "审核退货单", "parent": "supply_chain:purchase_return"},
        {"code": "supply_chain:purchase_return:complete", "name": "完成退货", "parent": "supply_chain:purchase_return"},
        {"code": "supply_chain:purchase_return:cancel", "name": "取消退货单", "parent": "supply_chain:purchase_return"},
        {"code": "supply_chain:alert:view", "name": "查看预警", "parent": "supply_chain:alert"},
        {"code": "supply_chain:alert:resolve", "name": "处理预警", "parent": "supply_chain:alert"},
        {"code": "supply_chain:trace:view", "name": "查看追溯", "parent": "supply_chain:trace"},
    ),
    features=("出库执行", "调拨执行", "销售退货", "采购退货", "库存预警", "库存追踪"),
    workflows=("销售出库自动生成应收", "采购退货自动联动应付", "调拨审批与执行"),
    field_rules=("多个详情页通过隐藏路由挂载",),
    default_rules=("业务单号默认复用平台编码规则",),
    public_services=("business_apps.supply_chain.services.OutboundService", "business_apps.supply_chain.services.TransferService"),
    export_metadata={
        "export_enabled": True,
        "must_export_with": ("crm", "supplier", "inventory", "sales", "purchase", "platform"),
        "has_frontend_pages": True,
        "seed_data": {"required": False, "keys": ()},
        "attachments_dependency": False,
        "task_log_dependency": True,
    },
)
