# Generated by Django 6.0.5 on 2026-06-15 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('inventory', '0002_product_max_stock_product_min_stock_stocktake_and_more'),
        ('organization', '0001_initial'),
        ('purchase', '0001_initial'),
        ('sales', '0002_salesorder_customer_name_snapshot_and_more'),
        ('supplier', '0002_supplier_currency_supplier_tax_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ==================== 销售出库 ====================
        migrations.CreateModel(
            name='OutboundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_no', models.CharField(max_length=50, unique=True, verbose_name='出库单号')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待审核'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department', verbose_name='所属部门')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_orders', to='sales.salesorder', verbose_name='销售订单')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='出库仓库')),
            ],
            options={
                'verbose_name': '销售出库单',
                'verbose_name_plural': '销售出库单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品名称快照')),
                ('product_code_snapshot', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品编码快照')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='出库数量')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='出库单价')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='出库金额')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('outbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supply_chain.outboundorder', verbose_name='出库单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '销售出库明细',
                'verbose_name_plural': '销售出库明细',
            },
        ),
        migrations.AddIndex(
            model_name='outboundorder',
            index=models.Index(fields=['outbound_no'], name='supply_chai_outbound_ee59bd_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundorder',
            index=models.Index(fields=['sales_order'], name='supply_chai_sales_or_3a77e5_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundorder',
            index=models.Index(fields=['warehouse'], name='supply_chai_warehouse_f6a6a1_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundorder',
            index=models.Index(fields=['status'], name='supply_chai_status_a1b2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundorder',
            index=models.Index(fields=['created_by'], name='supply_chai_created__d4e5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundorder',
            index=models.Index(fields=['dept'], name='supply_chai_dept_g7h8i9_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundorderitem',
            index=models.Index(fields=['outbound_order'], name='supply_chai_outbound_j1k2l3_idx'),
        ),
        # ==================== 仓库调拨 ====================
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.CharField(max_length=50, unique=True, verbose_name='调拨单号')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('IN_TRANSIT', '调拨中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department', verbose_name='所属部门')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_from_orders', to='inventory.warehouse', verbose_name='调出仓库')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_to_orders', to='inventory.warehouse', verbose_name='调入仓库')),
            ],
            options={
                'verbose_name': '仓库调拨单',
                'verbose_name_plural': '仓库调拨单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品名称快照')),
                ('product_code_snapshot', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品编码快照')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='调拨数量')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='商品')),
                ('transfer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supply_chain.transferorder', verbose_name='调拨单')),
            ],
            options={
                'verbose_name': '调拨明细',
                'verbose_name_plural': '调拨明细',
            },
        ),
        migrations.AddIndex(
            model_name='transferorder',
            index=models.Index(fields=['transfer_no'], name='supply_chai_transfer_m4n5o6_idx'),
        ),
        migrations.AddIndex(
            model_name='transferorder',
            index=models.Index(fields=['from_warehouse'], name='supply_chai_from_wha_p7q8r9_idx'),
        ),
        migrations.AddIndex(
            model_name='transferorder',
            index=models.Index(fields=['to_warehouse'], name='supply_chai_to_whare_s1t2u3_idx'),
        ),
        migrations.AddIndex(
            model_name='transferorder',
            index=models.Index(fields=['status'], name='supply_chai_status_v4w5x6_idx'),
        ),
        migrations.AddIndex(
            model_name='transferorder',
            index=models.Index(fields=['created_by'], name='supply_chai_created_y7z8a9_idx'),
        ),
        migrations.AddIndex(
            model_name='transferorderitem',
            index=models.Index(fields=['transfer_order'], name='supply_chai_transfer_b1c2d3_idx'),
        ),
        # ==================== 销售退货 ====================
        migrations.CreateModel(
            name='SalesReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(max_length=50, unique=True, verbose_name='退货单号')),
                ('customer_name_snapshot', models.CharField(blank=True, max_length=255, null=True, verbose_name='客户名称快照')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('APPROVED', '已审核'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='退货原因')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.customer', verbose_name='客户')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department', verbose_name='所属部门')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_orders', to='sales.salesorder', verbose_name='销售订单')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='退货仓库')),
            ],
            options={
                'verbose_name': '销售退货单',
                'verbose_name_plural': '销售退货单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品名称快照')),
                ('product_code_snapshot', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品编码快照')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='退货数量')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='商品')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supply_chain.salesreturnorder', verbose_name='退货单')),
            ],
            options={
                'verbose_name': '销售退货明细',
                'verbose_name_plural': '销售退货明细',
            },
        ),
        migrations.AddIndex(
            model_name='salesreturnorder',
            index=models.Index(fields=['return_no'], name='supply_chai_return_n_e4f5g6_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnorder',
            index=models.Index(fields=['customer'], name='supply_chai_customer_h7i8j9_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnorder',
            index=models.Index(fields=['sales_order'], name='supply_chai_sales_or_k1l2m3_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnorder',
            index=models.Index(fields=['warehouse'], name='supply_chai_warehouse_n4o5p6_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnorder',
            index=models.Index(fields=['status'], name='supply_chai_status_q7r8s9_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnorder',
            index=models.Index(fields=['created_by'], name='supply_chai_created_t1u2v3_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnorderitem',
            index=models.Index(fields=['return_order'], name='supply_chai_return_or_w4x5y6_idx'),
        ),
        # ==================== 采购退货 ====================
        migrations.CreateModel(
            name='PurchaseReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(max_length=50, unique=True, verbose_name='退货单号')),
                ('supplier_name_snapshot', models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商名称快照')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('APPROVED', '已审核'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='退货原因')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department', verbose_name='所属部门')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_orders', to='purchase.purchaseorder', verbose_name='采购订单')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier', verbose_name='供应商')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='退货仓库')),
            ],
            options={
                'verbose_name': '采购退货单',
                'verbose_name_plural': '采购退货单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品名称快照')),
                ('product_code_snapshot', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品编码快照')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='退货数量')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='商品')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supply_chain.purchasereturnorder', verbose_name='退货单')),
            ],
            options={
                'verbose_name': '采购退货明细',
                'verbose_name_plural': '采购退货明细',
            },
        ),
        migrations.AddIndex(
            model_name='purchasereturnorder',
            index=models.Index(fields=['return_no'], name='supply_chai_return_n_z7a8b9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnorder',
            index=models.Index(fields=['supplier'], name='supply_chai_supplier_c1d2e3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnorder',
            index=models.Index(fields=['purchase_order'], name='supply_chai_purchase_f4g5h6_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnorder',
            index=models.Index(fields=['warehouse'], name='supply_chai_warehouse_i7j8k9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnorder',
            index=models.Index(fields=['status'], name='supply_chai_status_l1m2n3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnorder',
            index=models.Index(fields=['created_by'], name='supply_chai_created_o4p5q6_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnorderitem',
            index=models.Index(fields=['return_order'], name='supply_chai_return_or_r7s8t9_idx'),
        ),
        # ==================== 库存预警 ====================
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', '低库存'), ('OUT_OF_STOCK', '缺货'), ('OVER_STOCK', '超库存')], max_length=20, verbose_name='预警类型')),
                ('current_qty', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='当前库存')),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='阈值')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='已处理')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库存预警',
                'verbose_name_plural': '库存预警',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryalert',
            index=models.Index(fields=['warehouse', 'product'], name='supply_chai_warehous_u1v2w3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryalert',
            index=models.Index(fields=['alert_type'], name='supply_chai_alert_ty_x4y5z6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryalert',
            index=models.Index(fields=['is_resolved'], name='supply_chai_is_resol_a7b8c9_idx'),
        ),
    ]
