# Generated by Django 6.0.5 on 2026-06-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0004_transferorder_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_APPROVAL', '待审核'), ('APPROVED', '已审核'), ('IN_TRANSIT', '调拨中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态'),
        ),
    ]
