# Generated by Django 6.0.5 on 2026-06-29 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0005_alter_transferorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='outboundorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_outbound_orders', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='outboundorder',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交时间'),
        ),
        migrations.AddField(
            model_name='outboundorder',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_outbound_orders', to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
        migrations.AddField(
            model_name='purchasereturnorder',
            name='finance_status',
            field=models.CharField(choices=[('PENDING', '待处理'), ('ADJUSTED', '已调整'), ('NOT_REQUIRED', '无需处理')], default='PENDING', max_length=20, verbose_name='财务处理状态'),
        ),
        migrations.AddField(
            model_name='salesreturnorder',
            name='finance_status',
            field=models.CharField(choices=[('PENDING', '待处理'), ('ADJUSTED', '已调整'), ('NOT_REQUIRED', '无需处理')], default='PENDING', max_length=20, verbose_name='财务处理状态'),
        ),
        migrations.AddField(
            model_name='transferorder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消时间'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待审核'), ('APPROVED', '已审核'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态'),
        ),
    ]
