# Generated by Django 6.0.5 on 2026-07-03 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0006_outboundorder_approved_at_outboundorder_approved_by_and_more'),
        ('tenant', '0003_fix_missing_tenant_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryalert',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alerts', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='outboundorder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_orders', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='outboundorderitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_order_items', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='purchasereturnorder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_return_orders', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='purchasereturnorderitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_return_order_items', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='salesreturnorder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_return_orders', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='salesreturnorderitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_return_order_items', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='transferorder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_orders', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='transferorderitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_order_items', to='tenant.tenant'),
        ),
    ]
