# Generated by Django 6.0.5 on 2026-07-03 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_auth', '0002_erpdepartment_erpuser_dept'),
        ('supply_chain', '0007_inventoryalert_tenant_outboundorder_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='处理人'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_outbound_orders', to='erp_auth.erpuser', verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpdepartment', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='outboundorder',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_outbound_orders', to='erp_auth.erpuser', verbose_name='提交人'),
        ),
        migrations.AlterField(
            model_name='purchasereturnorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='purchasereturnorder',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpdepartment', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='salesreturnorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='salesreturnorder',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpdepartment', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfer_orders', to='erp_auth.erpuser', verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpdepartment', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='inbound_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_confirmed_transfer_orders', to='erp_auth.erpuser', verbose_name='调入确认人'),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='outbound_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_confirmed_transfer_orders', to='erp_auth.erpuser', verbose_name='调出确认人'),
        ),
        migrations.AlterField(
            model_name='transferorder',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_transfer_orders', to='erp_auth.erpuser', verbose_name='提交人'),
        ),
    ]
