# Generated by Django 6.0.5 on 2026-07-13 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_auth', '0002_erpdepartment_erpuser_dept'),
        ('supply_chain', '0008_alter_inventoryalert_resolved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturnorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='purchasereturnorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_return_orders', to='erp_auth.erpuser', verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='purchasereturnorder',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交时间'),
        ),
        migrations.AddField(
            model_name='purchasereturnorder',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_purchase_return_orders', to='erp_auth.erpuser', verbose_name='提交人'),
        ),
        migrations.AddField(
            model_name='salesreturnorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='salesreturnorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sales_return_orders', to='erp_auth.erpuser', verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='salesreturnorder',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交时间'),
        ),
        migrations.AddField(
            model_name='salesreturnorder',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_sales_return_orders', to='erp_auth.erpuser', verbose_name='提交人'),
        ),
        migrations.AlterField(
            model_name='purchasereturnorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_APPROVAL', '待审核'), ('APPROVED', '已审核'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='salesreturnorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_APPROVAL', '待审核'), ('APPROVED', '已审核'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态'),
        ),
    ]
