# Generated by Django 6.0.5 on 2026-06-15 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DASHBOARD', '经营驾驶舱'), ('SALES_SUMMARY', '销售汇总'), ('SALES_TREND', '销售趋势'), ('SALES_PRODUCTS', '商品销售排行'), ('SALES_CUSTOMERS', '客户销售排行'), ('PURCHASE_SUMMARY', '采购汇总'), ('PURCHASE_TREND', '采购趋势'), ('PURCHASE_SUPPLIERS', '供应商采购排行'), ('INVENTORY_SUMMARY', '库存汇总'), ('INVENTORY_AGING', '库龄分析'), ('INVENTORY_ALERTS', '库存预警'), ('CUSTOMER_ANALYSIS', '客户分析'), ('SUPPLIER_ANALYSIS', '供应商分析'), ('PRODUCT_ANALYSIS', '商品分析')], max_length=30, verbose_name='报表类型')),
                ('status', models.CharField(choices=[('PENDING', '等待中'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='状态')),
                ('file_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='文件URL')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='文件名')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='查询参数')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '报表导出任务',
                'verbose_name_plural': '报表导出任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reportexporttask',
            index=models.Index(fields=['report_type'], name='reports_report_type_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexporttask',
            index=models.Index(fields=['status'], name='reports_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexporttask',
            index=models.Index(fields=['created_by'], name='reports_created_by_idx'),
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(verbose_name='快照日期')),
                ('report_type', models.CharField(choices=[('DASHBOARD', '经营驾驶舱'), ('SALES_SUMMARY', '销售汇总'), ('PURCHASE_SUMMARY', '采购汇总'), ('INVENTORY_SUMMARY', '库存汇总')], max_length=30, verbose_name='报表类型')),
                ('data_json', models.JSONField(verbose_name='快照数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '报表快照',
                'verbose_name_plural': '报表快照',
                'ordering': ['-snapshot_date'],
                'unique_together': {('snapshot_date', 'report_type')},
            },
        ),
        migrations.AddIndex(
            model_name='reportsnapshot',
            index=models.Index(fields=['snapshot_date'], name='reports_snapshot_date_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsnapshot',
            index=models.Index(fields=['report_type'], name='reports_snapshot_type_idx'),
        ),
    ]
