# Generated by Django 6.0.5 on 2026-06-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportexporttask',
            new_name='reports_rep_report__fe7618_idx',
            old_name='reports_report_type_idx',
        ),
        migrations.RenameIndex(
            model_name='reportexporttask',
            new_name='reports_rep_status_88cbd4_idx',
            old_name='reports_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reportexporttask',
            new_name='reports_rep_created_d49a17_idx',
            old_name='reports_created_by_idx',
        ),
        migrations.RenameIndex(
            model_name='reportsnapshot',
            new_name='reports_rep_snapsho_3d0ea9_idx',
            old_name='reports_snapshot_date_idx',
        ),
        migrations.RenameIndex(
            model_name='reportsnapshot',
            new_name='reports_rep_report__e3cdb7_idx',
            old_name='reports_snapshot_type_idx',
        ),
    ]
