# Generated by Django 6.0.5 on 2026-07-03 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_auth', '0002_erpdepartment_erpuser_dept'),
        ('reports', '0002_rename_reports_report_type_idx_reports_rep_report__fe7618_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportexporttask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser', verbose_name='创建人'),
        ),
    ]
