from __future__ import annotations


ERP_PERMISSION_DEPENDENCIES: dict[str, tuple[str, ...]] = {
    # Roles created before aging analysis had an action permission only carry
    # the page menu. Preserve their access when permissions are resynchronized.
    "ar:aging": ("ar:aging:view",),
    "ar:aging:view": ("crm:customer:reference",),
    "ap:aging": ("ap:aging:view",),
    "ap:aging:view": ("supplier:supplier:reference",),
    "ap:summary": ("ap:summary:view",),
    "inventory:transaction": ("inventory:transaction:view",),
    "purchase:stats": ("purchase:stats:view",),
    "sales:stats": ("sales:stats:view",),
    "system:log": ("system:log:view",),
    "system:user": ("system:user:view",),
    "system:dept": ("system:dept:view",),
    "system:role": ("system:role:view",),
    "inventory:warehouse:create": ("system:user:reference",),
    "inventory:warehouse:update": ("system:user:reference",),
    "inventory:product:create": ("inventory:category:reference", "inventory:unit:reference"),
    "inventory:product:update": ("inventory:category:reference", "inventory:unit:reference"),
    "inventory:inventory:adjust": ("inventory:product:reference", "inventory:warehouse:reference"),
    "inventory:stocktake:create": ("inventory:product:reference", "inventory:warehouse:reference"),
    "inventory:stocktake:update": ("inventory:product:reference", "inventory:warehouse:reference"),
    "purchase:order:create": (
        "supplier:supplier:reference",
        "inventory:product:reference",
        "inventory:warehouse:reference",
    ),
    "purchase:order:update": (
        "supplier:supplier:reference",
        "inventory:product:reference",
        "inventory:warehouse:reference",
    ),
    "purchase:receipt:create": (
        "supplier:supplier:reference",
        "inventory:product:reference",
        "inventory:warehouse:reference",
    ),
    "sales:order:create": (
        "crm:customer:reference",
        "inventory:product:reference",
        "inventory:warehouse:reference",
        "inventory:inventory:reference",
    ),
    "sales:order:update": (
        "crm:customer:reference",
        "inventory:product:reference",
        "inventory:warehouse:reference",
        "inventory:inventory:reference",
    ),
    "supplier:supplier:create": ("system:user:reference",),
    "supplier:supplier:update": ("system:user:reference",),
    "supplier:supplier:transfer": ("system:user:reference",),
    "crm:customer:create": ("system:user:reference",),
    "crm:customer:update": ("system:user:reference",),
    "crm:customer:transfer": ("system:user:reference",),
    "supply_chain:outbound:create": (
        "crm:customer:reference",
        "inventory:product:reference",
        "inventory:warehouse:reference",
    ),
    "supply_chain:outbound:update": (
        "crm:customer:reference",
        "inventory:product:reference",
        "inventory:warehouse:reference",
    ),
    "supply_chain:transfer:create": ("inventory:product:reference", "inventory:warehouse:reference"),
    "supply_chain:transfer:update": ("inventory:product:reference", "inventory:warehouse:reference"),
    "supply_chain:sales_return:create": (
        "crm:customer:reference",
        "inventory:product:reference",
        "inventory:warehouse:reference",
        "sales:order:reference",
    ),
    "supply_chain:sales_return:update": (
        "crm:customer:reference",
        "inventory:product:reference",
        "inventory:warehouse:reference",
        "sales:order:reference",
    ),
    "supply_chain:purchase_return:create": (
        "supplier:supplier:reference",
        "inventory:product:reference",
        "inventory:warehouse:reference",
        "inventory:inventory:reference",
    ),
    "supply_chain:purchase_return:update": (
        "supplier:supplier:reference",
        "inventory:product:reference",
        "inventory:warehouse:reference",
        "inventory:inventory:reference",
    ),
    "finance:cash:create": ("system:user:reference",),
    "finance:cash:update": ("system:user:reference",),
    "ar:receipt:create": ("crm:customer:reference", "finance:cash:reference"),
    "ar:receipt:update": ("crm:customer:reference", "finance:cash:reference"),
    "ar:receivable:generate": ("sales:order:reference",),
    "ar:refund:create": ("crm:customer:reference", "finance:cash:reference"),
    "ar:refund:update": ("crm:customer:reference", "finance:cash:reference"),
    "ap:payment:create": ("supplier:supplier:reference", "finance:cash:reference"),
    "ap:payment:update": ("supplier:supplier:reference", "finance:cash:reference"),
    "ap:refund:create": ("supplier:supplier:reference", "finance:cash:reference"),
    "ap:refund:update": ("supplier:supplier:reference", "finance:cash:reference"),
    "ap:allocation:create": ("supplier:supplier:reference", "finance:cash:reference"),
    "ap:allocation:update": ("supplier:supplier:reference", "finance:cash:reference"),
}
