# Generated by Django 6.0.5 on 2026-06-26 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='账户名称')),
                ('type', models.CharField(choices=[('CASH', '现金'), ('BANK', '银行账户'), ('ALIPAY', '支付宝'), ('WECHAT', '微信'), ('OTHER', '其他')], default='BANK', max_length=20)),
                ('account_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='账号/卡号')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='开户行')),
                ('currency', models.CharField(default='CNY', max_length=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='当前余额')),
                ('status', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '现金账户',
                'verbose_name_plural': '现金账户',
            },
        ),
        migrations.CreateModel(
            name='FinancialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True, verbose_name='快照日期')),
                ('total_ar', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='总应收')),
                ('total_ap', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='总应付')),
                ('total_cash', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='现金总余额')),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='当日收款额')),
                ('daily_expense', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='当日付款额')),
            ],
            options={
                'verbose_name': '财务统计快照',
                'verbose_name_plural': '财务统计快照',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='FinanceExportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=50)),
                ('parameters', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', '排队中'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=20)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '财务导出任务',
                'verbose_name_plural': '财务导出任务',
            },
        ),
    ]
