# Generated by Codex on 2026-06-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_cash_accounts(apps, schema_editor):
    CashAccount = apps.get_model('finance', 'CashAccount')
    CashAccountTransaction = apps.get_model('finance', 'CashAccountTransaction')

    for account in CashAccount.objects.all():
        account.account_type = account.type
        if not account.opening_balance_date:
            account.opening_balance_date = account.created_at.date()
        account.save(update_fields=['account_type', 'opening_balance_date'])

        if account.current_balance and not CashAccountTransaction.objects.filter(
            cash_account=account,
            source_type='OPENING_BALANCE',
        ).exists():
            CashAccountTransaction.objects.create(
                cash_account=account,
                transaction_date=account.opening_balance_date,
                direction='INFLOW' if account.current_balance >= 0 else 'OUTFLOW',
                amount=abs(account.current_balance),
                balance_after=account.current_balance,
                source_type='OPENING_BALANCE',
                source_document_no_snapshot=f'OPEN-{account.id}',
                remark='迁移补录期初余额',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashaccount',
            name='account_type',
            field=models.CharField(choices=[('CASH', '现金'), ('BANK', '银行账户'), ('ALIPAY', '支付宝'), ('WECHAT', '微信'), ('OTHER', '其他')], default='BANK', max_length=20, verbose_name='账户类型'),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='opening_balance_date',
            field=models.DateField(blank=True, null=True, verbose_name='期初余额日期'),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='缓存字段，由资金流水或后续总账/凭证汇总回写', max_digits=15, verbose_name='当前余额'),
        ),
        migrations.CreateModel(
            name='CashAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='资金日期')),
                ('direction', models.CharField(choices=[('INFLOW', '流入'), ('OUTFLOW', '流出')], max_length=20, verbose_name='资金方向')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='变动金额')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='变动后余额')),
                ('source_type', models.CharField(choices=[('OPENING_BALANCE', '期初余额'), ('AR_RECEIPT', '应收收款执行'), ('AP_PAYMENT', '应付付款执行'), ('MANUAL', '手工调整')], max_length=30, verbose_name='来源类型')),
                ('source_id', models.IntegerField(blank=True, null=True, verbose_name='来源单据ID')),
                ('source_document_no_snapshot', models.CharField(blank=True, max_length=100, null=True, verbose_name='来源单号快照')),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.cashaccount')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '资金流水',
                'verbose_name_plural': '资金流水',
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.RunPython(backfill_cash_accounts, migrations.RunPython.noop),
    ]
