# Generated by Django 6.0.5 on 2026-07-03 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_cashaccount_account_type_opening_balance_date_and_more'),
        ('tenant', '0003_fix_missing_tenant_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashaccount',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_accounts', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='cashaccounttransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_account_transactions', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='financeexporttask',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_export_tasks', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='financialsnapshot',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_snapshots', to='tenant.tenant'),
        ),
    ]
