# Generated by Django 6.0.5 on 2026-07-03 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_auth', '0002_erpdepartment_erpuser_dept'),
        ('finance', '0003_cashaccount_tenant_cashaccounttransaction_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccounttransaction',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='financeexporttask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser'),
        ),
    ]
