# Generated by Django 6.0.5 on 2026-06-26 02:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('organization', '0001_initial'),
        ('sales', '0002_salesorder_customer_name_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ARAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_no', models.CharField(max_length=50, unique=True, verbose_name='应收单号')),
                ('source_type', models.CharField(default='OUTBOUND', max_length=50, verbose_name='来源类型')),
                ('source_id', models.IntegerField(verbose_name='来源ID')),
                ('source_no', models.CharField(max_length=50, verbose_name='来源单号')),
                ('currency_code', models.CharField(default='CNY', max_length=10, verbose_name='币种')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=15, verbose_name='汇率')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='应收金额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='已收金额')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='余额')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='到期日')),
                ('status', models.CharField(choices=[('PENDING', '待收款'), ('PARTIAL', '部分收款'), ('PAID', '已结清'), ('OVERDUE', '已逾期'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='状态')),
                ('overdue_days', models.IntegerField(default=0, verbose_name='逾期天数')),
                ('customer_name_snapshot', models.CharField(blank=True, max_length=255, null=True, verbose_name='客户名称快照')),
                ('base_currency_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='本币金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ar_accounts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_accounts', to='crm.customer', verbose_name='客户')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department', verbose_name='所属部门')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ar_accounts', to='sales.salesorder', verbose_name='销售订单')),
            ],
            options={
                'verbose_name': '应收账款',
                'verbose_name_plural': '应收账款',
                'db_table': 'ar_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AROperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50, verbose_name='对象类型')),
                ('object_id', models.IntegerField(verbose_name='对象ID')),
                ('action', models.CharField(choices=[('GENERATE', '生成应收'), ('RECEIPT', '创建收款'), ('APPROVE', '审核'), ('CANCEL_APPROVE', '取消审核'), ('ALLOCATE', '核销'), ('CANCEL_ALLOCATE', '取消核销'), ('RECALCULATE', '重算'), ('STATUS_CHANGE', '状态变更'), ('CANCEL', '取消'), ('RECOVER', '恢复')], max_length=50, verbose_name='操作类型')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='旧值')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='新值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '应收操作日志',
                'verbose_name_plural': '应收操作日志',
                'db_table': 'ar_operation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ARReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=50, unique=True, verbose_name='收款单号')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='收款金额')),
                ('currency_code', models.CharField(default='CNY', max_length=10, verbose_name='币种')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=15, verbose_name='汇率')),
                ('receipt_method', models.CharField(choices=[('BANK', '银行转账'), ('CASH', '现金'), ('ALIPAY', '支付宝'), ('WECHAT', '微信支付'), ('OTHER', '其他')], default='BANK', max_length=20, verbose_name='收款方式')),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='银行账户')),
                ('receipt_date', models.DateField(verbose_name='收款日期')),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已审核'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ar_receipts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_receipts', to='crm.customer', verbose_name='客户')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '收款单',
                'verbose_name_plural': '收款单',
                'db_table': 'ar_receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ARAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='核销金额')),
                ('allocation_date', models.DateField(verbose_name='核销日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='ar_receivable.araccount', verbose_name='应收单')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ar_allocations', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='ar_receivable.arreceipt', verbose_name='收款单')),
            ],
            options={
                'verbose_name': '核销记录',
                'verbose_name_plural': '核销记录',
                'db_table': 'ar_allocations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ARReceiptAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_url', models.CharField(max_length=500, verbose_name='文件URL')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ar_receivable.arreceipt', verbose_name='收款单')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_ar_receipt_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '收款单附件',
                'verbose_name_plural': '收款单附件',
                'db_table': 'ar_receipt_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ARSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(verbose_name='快照日期')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='应收总额')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='已收总额')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='未收余额')),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='逾期金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_snapshots', to='crm.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '应收快照',
                'verbose_name_plural': '应收快照',
                'db_table': 'ar_snapshots',
                'ordering': ['-snapshot_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='araccount',
            index=models.Index(fields=['ar_no'], name='idx_ar_account_no'),
        ),
        migrations.AddIndex(
            model_name='araccount',
            index=models.Index(fields=['customer'], name='idx_ar_account_customer'),
        ),
        migrations.AddIndex(
            model_name='araccount',
            index=models.Index(fields=['sales_order'], name='idx_ar_account_sales_order'),
        ),
        migrations.AddIndex(
            model_name='araccount',
            index=models.Index(fields=['status'], name='idx_ar_account_status'),
        ),
        migrations.AddIndex(
            model_name='araccount',
            index=models.Index(fields=['due_date'], name='idx_ar_account_due_date'),
        ),
        migrations.AddIndex(
            model_name='araccount',
            index=models.Index(fields=['dept'], name='idx_ar_account_dept'),
        ),
        migrations.AddIndex(
            model_name='araccount',
            index=models.Index(fields=['created_by'], name='idx_ar_account_created_by'),
        ),
        migrations.AddIndex(
            model_name='aroperationlog',
            index=models.Index(fields=['object_type', 'object_id'], name='idx_ar_log_object'),
        ),
        migrations.AddIndex(
            model_name='aroperationlog',
            index=models.Index(fields=['action'], name='idx_ar_log_action'),
        ),
        migrations.AddIndex(
            model_name='aroperationlog',
            index=models.Index(fields=['created_at'], name='idx_ar_log_created_at'),
        ),
        migrations.AddIndex(
            model_name='arreceipt',
            index=models.Index(fields=['receipt_no'], name='idx_ar_receipt_no'),
        ),
        migrations.AddIndex(
            model_name='arreceipt',
            index=models.Index(fields=['customer'], name='idx_ar_receipt_customer'),
        ),
        migrations.AddIndex(
            model_name='arreceipt',
            index=models.Index(fields=['status'], name='idx_ar_receipt_status'),
        ),
        migrations.AddIndex(
            model_name='arreceipt',
            index=models.Index(fields=['receipt_date'], name='idx_ar_receipt_date'),
        ),
        migrations.AddIndex(
            model_name='arreceipt',
            index=models.Index(fields=['dept'], name='idx_ar_receipt_dept'),
        ),
        migrations.AddIndex(
            model_name='arreceipt',
            index=models.Index(fields=['created_by'], name='idx_ar_receipt_created_by'),
        ),
        migrations.AddIndex(
            model_name='arallocation',
            index=models.Index(fields=['receipt'], name='idx_ar_allocation_receipt'),
        ),
        migrations.AddIndex(
            model_name='arallocation',
            index=models.Index(fields=['account'], name='idx_ar_allocation_account'),
        ),
        migrations.AddIndex(
            model_name='arallocation',
            index=models.Index(fields=['allocation_date'], name='idx_ar_allocation_date'),
        ),
        migrations.AddConstraint(
            model_name='arallocation',
            constraint=models.UniqueConstraint(fields=('receipt', 'account'), name='unique_ar_allocation'),
        ),
        migrations.AddIndex(
            model_name='arreceiptattachment',
            index=models.Index(fields=['receipt'], name='idx_ar_receipt_attachment_receipt'),
        ),
        migrations.AddIndex(
            model_name='arsnapshot',
            index=models.Index(fields=['snapshot_date'], name='idx_ar_snapshot_date'),
        ),
        migrations.AddIndex(
            model_name='arsnapshot',
            index=models.Index(fields=['customer'], name='idx_ar_snapshot_customer'),
        ),
    ]
