# Generated by Django 6.0.5 on 2026-06-26 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ar_receivable', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='arreceiptattachment',
            new_name='idx_ar_attach_receipt',
            old_name='idx_ar_receipt_attachment_receipt',
        ),
    ]
