# Generated by Django 6.0.5 on 2026-06-26 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_receivable', '0002_rename_idx_ar_receipt_attachment_receipt_idx_ar_attach_receipt'),
        ('crm', '0001_initial'),
        ('organization', '0001_initial'),
        ('sales', '0002_salesorder_customer_name_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=50, unique=True, verbose_name='收款单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='收款总额')),
                ('unwritten_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='未核销金额')),
                ('receipt_date', models.DateField(verbose_name='收款日期')),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', '银行转账'), ('WECHAT', '微信支付'), ('ALIPAY', '支付宝'), ('CASH', '现金'), ('OTHER', '其他')], default='BANK_TRANSFER', max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='交易流水号/支票号')),
                ('status', models.CharField(choices=[('UNWRITTEN', '未核销'), ('PARTIAL_WRITTEN', '部分核销'), ('WRITTEN', '已核销'), ('CANCELLED', '已作废')], default='UNWRITTEN', max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '收款单',
                'verbose_name_plural': '收款单',
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivable_no', models.CharField(max_length=50, unique=True, verbose_name='应收单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='应收总额')),
                ('written_off_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='已核销金额')),
                ('due_date', models.DateField(verbose_name='到期日')),
                ('status', models.CharField(choices=[('UNPAID', '未收款'), ('PARTIAL_PAID', '部分收款'), ('PAID', '已结清'), ('CANCELLED', '已取消')], default='UNPAID', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '应收账款',
                'verbose_name_plural': '应收账款',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_off_no', models.CharField(max_length=50, unique=True, verbose_name='核销单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='核销金额')),
                ('write_off_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '核销记录',
                'verbose_name_plural': '核销记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='araccount',
            name='idx_ar_account_no',
        ),
        migrations.RemoveIndex(
            model_name='araccount',
            name='idx_ar_account_customer',
        ),
        migrations.RemoveIndex(
            model_name='araccount',
            name='idx_ar_account_sales_order',
        ),
        migrations.RemoveIndex(
            model_name='araccount',
            name='idx_ar_account_status',
        ),
        migrations.RemoveIndex(
            model_name='araccount',
            name='idx_ar_account_due_date',
        ),
        migrations.RemoveIndex(
            model_name='araccount',
            name='idx_ar_account_dept',
        ),
        migrations.RemoveIndex(
            model_name='araccount',
            name='idx_ar_account_created_by',
        ),
        migrations.RemoveIndex(
            model_name='arallocation',
            name='idx_ar_allocation_receipt',
        ),
        migrations.RemoveIndex(
            model_name='arallocation',
            name='idx_ar_allocation_account',
        ),
        migrations.RemoveIndex(
            model_name='arallocation',
            name='idx_ar_allocation_date',
        ),
        migrations.RemoveConstraint(
            model_name='arallocation',
            name='unique_ar_allocation',
        ),
        migrations.RemoveIndex(
            model_name='aroperationlog',
            name='idx_ar_log_object',
        ),
        migrations.RemoveIndex(
            model_name='aroperationlog',
            name='idx_ar_log_action',
        ),
        migrations.RemoveIndex(
            model_name='aroperationlog',
            name='idx_ar_log_created_at',
        ),
        migrations.RemoveIndex(
            model_name='arreceipt',
            name='idx_ar_receipt_no',
        ),
        migrations.RemoveIndex(
            model_name='arreceipt',
            name='idx_ar_receipt_customer',
        ),
        migrations.RemoveIndex(
            model_name='arreceipt',
            name='idx_ar_receipt_status',
        ),
        migrations.RemoveIndex(
            model_name='arreceipt',
            name='idx_ar_receipt_date',
        ),
        migrations.RemoveIndex(
            model_name='arreceipt',
            name='idx_ar_receipt_dept',
        ),
        migrations.RemoveIndex(
            model_name='arreceipt',
            name='idx_ar_receipt_created_by',
        ),
        migrations.RemoveIndex(
            model_name='arreceiptattachment',
            name='idx_ar_attach_receipt',
        ),
        migrations.RemoveIndex(
            model_name='arsnapshot',
            name='idx_ar_snapshot_date',
        ),
        migrations.RemoveIndex(
            model_name='arsnapshot',
            name='idx_ar_snapshot_customer',
        ),
        migrations.AddField(
            model_name='receipt',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receivables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivable',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='sales.salesorder'),
        ),
        migrations.AddField(
            model_name='writeoff',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writeoff',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_offs', to='ar_receivable.receipt'),
        ),
        migrations.AddField(
            model_name='writeoff',
            name='receivable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_offs', to='ar_receivable.receivable'),
        ),
        migrations.RemoveField(
            model_name='arallocation',
            name='account',
        ),
        migrations.RemoveField(
            model_name='arallocation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='arallocation',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='aroperationlog',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='arreceipt',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='arreceipt',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='arreceipt',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='arreceiptattachment',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='arreceiptattachment',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='arsnapshot',
            name='customer',
        ),
        migrations.DeleteModel(
            name='ARAccount',
        ),
        migrations.DeleteModel(
            name='ARAllocation',
        ),
        migrations.DeleteModel(
            name='AROperationLog',
        ),
        migrations.DeleteModel(
            name='ARReceipt',
        ),
        migrations.DeleteModel(
            name='ARReceiptAttachment',
        ),
        migrations.DeleteModel(
            name='ARSnapshot',
        ),
    ]
