# Generated by Django 6.0.5 on 2026-06-26 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_receivable', '0003_receipt_receivable_writeoff_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.cashaccount', verbose_name='收款账户'),
        ),
    ]
