# Generated by Codex on 2026-06-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_receivable', '0004_receipt_cash_account'),
        ('supply_chain', '0004_transferorder_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivable',
            name='outbound_order',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='receivables',
                to='supply_chain.outboundorder',
            ),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['outbound_order'], name='ar_receivab_outboun_6ac74e_idx'),
        ),
    ]
