# Generated by Codex on 2026-06-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_receivable', '0005_receivable_outbound_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(
                choices=[
                    ('DRAFT', '草稿'),
                    ('UNWRITTEN', '未核销'),
                    ('PARTIAL_WRITTEN', '部分核销'),
                    ('WRITTEN', '已核销'),
                    ('CANCELLED', '已作废'),
                ],
                default='DRAFT',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='receipt',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='approved_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='approved_receipts',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
