# Generated by Django 6.0.5 on 2026-06-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ar_receivable', '0006_receipt_approval_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='receivable',
            new_name='ar_receivab_outboun_268853_idx',
            old_name='ar_receivab_outboun_6ac74e_idx',
        ),
    ]
