# Generated by Codex on 2026-06-29

from django.db import migrations, models


def backfill_receivable_and_receipt_fields(apps, schema_editor):
    Receivable = apps.get_model('ar_receivable', 'Receivable')
    Receipt = apps.get_model('ar_receivable', 'Receipt')

    Receivable.objects.filter(outbound_order_id__isnull=False).update(source_type='OUTBOUND_ORDER')
    Receivable.objects.filter(outbound_order_id__isnull=True, sales_order_id__isnull=False).update(source_type='SALES_ORDER')
    Receivable.objects.filter(outbound_order_id__isnull=True, sales_order_id__isnull=True).update(source_type='MANUAL')

    for receipt in Receipt.objects.exclude(status='DRAFT').filter(executed_at__isnull=True):
        receipt.executed_at = receipt.approved_at or receipt.created_at
        receipt.save(update_fields=['executed_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('ar_receivable', '0007_rename_ar_receivab_outboun_6ac74e_idx_ar_receivab_outboun_268853_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivable',
            name='source_type',
            field=models.CharField(
                choices=[
                    ('SALES_ORDER', '销售订单'),
                    ('OUTBOUND_ORDER', '销售出库单'),
                    ('SALES_RETURN', '销售退货单'),
                    ('MANUAL', '手工创建'),
                ],
                default='OUTBOUND_ORDER',
                max_length=50,
                verbose_name='来源类型',
            ),
        ),
        migrations.AddField(
            model_name='receipt',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='执行时间'),
        ),
        migrations.AddField(
            model_name='writeoff',
            name='write_off_type',
            field=models.CharField(
                choices=[
                    ('RECEIPT', '收款核销'),
                    ('RETURN_OFFSET', '退货冲减'),
                ],
                default='RECEIPT',
                max_length=30,
                verbose_name='核销类型',
            ),
        ),
        migrations.RunPython(backfill_receivable_and_receipt_fields, migrations.RunPython.noop),
    ]
