# Generated by Django 6.0.5 on 2026-07-03 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_receivable', '0008_receivable_source_type_receipt_executed_at_and_more'),
        ('tenant', '0003_fix_missing_tenant_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='writeoff',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='write_offs', to='tenant.tenant'),
        ),
    ]
