# Generated by Django 6.0.5 on 2026-07-03 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_receivable', '0009_receipt_tenant_receivable_tenant_writeoff_tenant'),
        ('erp_auth', '0002_erpdepartment_erpuser_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_receipts', to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpdepartment'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receivables', to='erp_auth.erpuser'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpdepartment'),
        ),
        migrations.AlterField(
            model_name='writeoff',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpuser'),
        ),
    ]
