# Generated by Django 6.0.5 on 2026-07-12 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_receivable', '0011_writeoff_receipt_nullable'),
        ('crm', '0007_alter_contact_created_at_alter_contact_customer_and_more'),
        ('erp_auth', '0002_erpdepartment_erpuser_dept'),
        ('finance', '0004_alter_cashaccounttransaction_operator_and_more'),
        ('tenant', '0003_fix_missing_tenant_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivable',
            name='status',
            field=models.CharField(choices=[('UNPAID', '未收款'), ('PARTIAL_PAID', '部分收款'), ('PAID', '已结清'), ('REFUND_PENDING', '待退款'), ('PARTIAL_REFUNDED', '部分退款'), ('REFUNDED', '已退款'), ('CANCELLED', '已取消')], default='UNPAID', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='CustomerRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_no', models.CharField(max_length=50, unique=True, verbose_name='退款单号')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='退款金额')),
                ('refund_date', models.DateField(verbose_name='退款日期')),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', '银行转账'), ('WECHAT', '微信支付'), ('ALIPAY', '支付宝'), ('CASH', '现金'), ('OTHER', '其他')], default='BANK_TRANSFER', max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='交易流水号/支票号')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('APPROVED', '已审核'), ('COMPLETED', '已退款'), ('CANCELLED', '已作废')], default='DRAFT', max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_customer_refunds', to='erp_auth.erpuser')),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.cashaccount', verbose_name='退款账户')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_refunds', to='erp_auth.erpuser')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='crm.customer')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_auth.erpdepartment')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='ar_receivable.receivable', verbose_name='对应红字应收')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_refunds', to='tenant.tenant')),
            ],
            options={
                'verbose_name': '客户退款单',
                'verbose_name_plural': '客户退款单',
                'ordering': ['-refund_date', '-created_at'],
            },
        ),
    ]
